### ISSUE TITLE
Could we compile from source in Fedora?

### ISSUE THREAD

**Issue by YiruS** [intel-isl/Open3D#1052]
Hi there,

I tried to compile from source but currently it seems only support Ubuntu, Windows and OSX. I wonder if it's possible to compile the source in other Linux machine, like Fedora? 

The context is that when I tried to use the sample code `downpcd = pcd.voxel_down_sample(voxel_size=0.05)` , it shows 
"**AttributeError**: 'open3d.open3d.geometry.PointCloud' object has no attribute 'voxel_down_sample'". 

Then based on some posts, I tried to import `from open3d.open3d.geometry import voxel_down_sample,estimate_normals` and run `downpcd = voxel_down_sample(pcd)`. Still, it shows "**TypeError: voxel_down_sample(): incompatible function arguments**. The following argument types are supported: 1. (input: open3d.open3d.geometry.PointCloud, voxel_size: float) -> open3d.open3d.geometry.PointCloud".

Any suggestions are appreciated! Thanks!

**Comment by yxlao** [comment]
**Q1: Fedora?**
Yes, it shall be possible to compile with Fedora. I haven't tested it. There could be some differences at dependency installation. But in principle, it shall work. Please let us know your findings.

**Q2: `downpcd = pcd.voxel_down_sample(voxel_size=0.05)`**
This is the correct API in our latest master branch. Visit http://www.open3d.org/docs/latest/ and search `voxel_down_sample`.

**Q3: `from open3d.open3d.geometry import voxel_down_sample; downpcd = voxel_down_sample(pcd)`**
Looks like you're trying to run the old API (e.g. 0.7.0) from pip or conda. You need the `voxel_size` argument. Visit http://www.open3d.org/docs/release/ and search `voxel_down_sample`. 
The usage is
```
# 0.7.0
import open3d as o3d
downpcd = o3d.geometry.voxel_down_sample(pcd, voxel_size)
```

PS: We recently introduced a docs version switcher with https://github.com/intel-isl/Open3D/pull/1055 . I think this issue is due to the confusion on docs version. Hope this helps.
