### ISSUE TITLE
what do min_bound, max_bound do in voxel_down_sample_and_trace?

### ISSUE THREAD

**Issue by lvgeng** [intel-isl/Open3D#1085]
open3d.geometry.voxel_down_sample_and_trace(input, voxel_size, min_bound, max_bound, approximate_class=False)
http://www.open3d.org/docs/release/python_api/open3d.geometry.voxel_down_sample_and_trace.html

According to the documents it should have similar behaviour with 
geometry.Voxel_Down_Sample

However the results are quite different with same voxel_size. And sometime there are points quite close to each other in the downsampled results.

I assume that is because of the min_bound and the max_bound, but what do them do? The document says they are "Minimum/Maximum coordinate of voxel boundaries"... but the description does not give any more information, and I have no idea what they are actually affecting after trying different values.
Even further, what does approximate_class do?

**Comment by yxlao** [comment]
See the implementation:

https://github.com/intel-isl/Open3D/blob/11a27bfaa83e57cec9c13afd4b7f4bcb60ff643a/src/Open3D/Geometry/DownSample.cpp#L294-L361 

**Q: min_bound and the max_bound, but what do they do?**
`min_bound` and `max_bound` are both size `(3,)` arrays,  specifying `min_bound` and `max_bound` of the resulting `VoxelGrid`. Roughly speaking, you get `(max_bound - min_bound) / voxel_size` voxel cells along the 3 dimensions.

**Q: what does approximate_class do?**
If yes, the output color will be the averaged color of the points that fall in this cell. Otherwise, the majority color will be used. 
```
if (approximate_class) {
     output->colors_.push_back(accpoint.second.GetMaxClass());
} else {
     output->colors_.push_back(accpoint.second.GetAverageColor());
}
```

**Comment by planerymist** [comment]
Thanks a lot for your explanation. I'm interested in the part with approximate_class, because we do not want the colors to be averaged. We need the original colors.
The approximate_class option sounds like:
if there are three blue points and one green point in one cell, the output is one blue point. Unfortunately, in my case the output are only black points. But in the input is no single black point! Is this a bug? Am I doing something wrong?
```
min_bound = pcd.get_min_bound()
max_bound = pcd.get_max_bound()
downpcd, i, a = pcd.voxel_down_sample_and_trace(self.voxel_size, min_bound, max_bound, True)
print(downpcd)
```

**Comment by germanros1987** [comment]
@planerymist please do not kidnap the conversation.
