### ISSUE TITLE
Open3d is embedded in PyQt for visualization

### ISSUE THREAD

**Issue by JavaAiNiU** [intel-isl/Open3D#1161]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when  I want to embed visual interfaces in pyqt and other back ends, I don't see any good way to do that with apps like vispy.

**Describe the solution you'd like**
I feel that the ability to embed visual interfaces into backends such as PyQt is very useful for developing GUI applications with open3d.

**Describe alternatives you've considered**
Now I'm trying to use mayavi embedded in GUI applications instead of open3d visualization.

**Additional context**

**Comment by Lu-jiang** [comment]
Have you solved this problem? i am very sad because of this problem.

**Comment by JavaAiNiU** [comment]
> Have you solved this problem? i am very sad because of this problem.

Sorry,I did not solve.Visualization now uses open3d's own visualization functions.

**Comment by mastrogiorgis** [comment]
Hi there,
open3d has its own visualisation functions but QT is ahead of things here and it would be nice if we could export a widget straight to PyQt. Same way as VTK can.
Thanks

**Comment by ArlenisChS** [comment]
Still nothing on this??

**Comment by JavaAiNiU** [comment]
> Hi there,
> open3d has its own visualisation functions but QT is ahead of things here and it would be nice if we could export a widget straight to PyQt. Same way as VTK can.
> Thanks

ok，tks.

**Comment by germanros1987** [comment]
Forget about PyQT and VTK. We have created our own GUI module, natively integrated with Open3D and with python wrappers. This is coming out as part of Open3D 0.11, expected in September. I know it took a while, but it is almost here. In fact, if you are curious you can play with master. You will find a few examples like [vis-gui.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/GUI/vis-gui.py).

**Comment by Zumbalamambo** [comment]
@Lu-jiang I'm very sad too because of that

**Comment by prewettg** [comment]
0.11 has been released and has python bindings for using the new rendering system. It comes with several examples, with [examples/python/gui/vis-gui.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/GUI/vis-gui.py) being the most full-featured. Mixing user interface elements and OpenGL has never been a simple process, and as a team we decided to use package Dear ImGUI into our own GUI to minimize external dependencies. Furthermore, the rendering library we are using, Filament, prefers to drawing directly into a native window via a separate thread. Unfortunately, this means that we cannot offer Qt support. If Qt is a requirement for you, you can use the Open3D algorithms and use a rendering library that supports Qt to do the rendering. Otherwise, our intention for our GUI library is that it should be a reasonably full-featured GUI toolkit, so if there is something that you are unable to do with it, please let us know.

**Comment by notaTeapot** [comment]
You can capture an active Open3D Window in PyQt/PySide if you need to: https://github.com/isl-org/Open3D/discussions/4668

**Comment by fennecinspace** [comment]
I would like this to be reopened please, because even though it's good that there is your own GUI model. PyQT is a leader and most people need the widget, since both open source and commercial apps will resort to PyQT.
