### ISSUE TITLE
How to set light?

### ISSUE THREAD

**Issue by chenerg** [intel-isl/Open3D#1238]
Is there document or function for setting real light source?

**Comment by syncle** [comment]
I am not sure what "real light source" means, but if you mean to say the environment map, Open3D doesn't have it yet. We are preparing enhanced rendering though.

**Comment by ChimMeya** [comment]
Hi Mr @syncle,
You still working on it? because without lighting we can't show the 3D effect.

**Comment by tfy14esa** [comment]
Hi,
I am also wondering about this, because I have not yet been able to get the phong shader working, even though I set the parameter light_on = True in the open3d.visualization.RenderOption class. Furthermore, when I create a default RenderOption object, there are 4 light sources that are created, but those are not covered in the documentation. 

Am I missing something?

Great work with Open3D by the way! I really appreciate it.
