### ISSUE TITLE
Incomplete installation on ARM architectures (Jetson TX2, Ubuntu 18.04)

### ISSUE THREAD

**Issue by cosama** [intel-isl/Open3D#1249]
On a Ubuntu 18.04 installation with ARM architecture (I tried it on a Jetson TX2) neither `pip install open3d --user` nor `pip install open3d-python --user` will install a working `open3d` installation.

* package open3d: Downloads and installs `open3d-0+unknown`, which results in a folder `site-packages/open3d-0+unknown.dist-info/` being created, however when typing `import open3d` in `python` it won't find the package: `ImportError: No module named open3d`. No folder `site-package/open3d` is present.

* package open3d-python: When installing this package then it downloads open3d version 0.3.0, which seems to be affected by a bug fixed in a later pull request: https://github.com/intel-isl/Open3D/pull/625. I assume this is a legacy package and maybe should be removed.

* Building the pip-package from source (I only tested it with `pip2`) seems to work fine.

**Expected behavior**
* If using pip on such a system it either should install a working version or complain that the architecture is not supported.
* Might be related to https://github.com/intel-isl/Open3D/issues/841

**Environment:**
 - ARMv8 (L4T, Jetson TX2)
 - Ubuntu 18.04
 - Tested with both `pip2` and `pip3`

**Comment by yxlao** [comment]
This is expected. On ARM we currently don't release pre-compiled `pip` or `conda` binary yet. Please build from source for ARM.

**Comment by cosama** [comment]
@yxlao Thanks for the reply. That's what I assumed. What I was surprised was that the `pip` actually doesn't fail, but installs something non-functional. I have seen other frameworks fail with a message pointing out that the current architecture is not supported. It would be great if that would happen here too.`

**Comment by yxlao** [comment]
@cosama Thanks. That's a good point. 

- For `pip install open3d`
  - I've deleted an outdated release. Now it shall fail with a message "architecture not supported". 
- For `pip install open3d-python` (which is deprecated)
  - The reason why ARM platform gets the `0.3.0` is that the package was marked as `any`: `open3d_python-0.3.0.0-py2.py3-none-any.whl`
  - Since `0.4.0` we've added the architecture marker e.g. `x86_64`: e.g. `open3d_python-0.4.0.0-cp27-cp27mu-manylinux1_x86_64.whl`.

Our plan is to do re-upload of old releases to the `open3d` repo with architecture marker and completely deprecate `open3d-python`.

**Comment by cosama** [comment]
@yxlao. Thanks for the quick actions. I can confirm that `pip install open3d` now fails with the appropriate message on a TX2. As `open3d-python` is deprecated I think it is okay to leave it as it is for now. Feel free to close this issue.

By the way, I really appreciate having `open3d` around, I use it for pretty much all my point cloud related tasks and it made my life so much easier recently.

**Comment by yxlao** [comment]
thanks, glad it's helpful to you, let us know if you run into any other issues on ARM
