### ISSUE TITLE
ReconstructionSystem with realsense at higher resolution

### ISSUE THREAD

**Issue by argosvr** [intel-isl/Open3D#1273]
I'm trying to use a robotic system to make a bodyscan (some stepper motors to take different angles to take a complete view).
I'm trying to get a better resolution using voxel size,  MaxClamp and MinClamp and I get the result I want using a modified version of your sensor capture for realsense and reconstructionSystem with voxel size at 0.05, 0.04 and 0.03 (of course I adapt the voxel size and the max depth and min depth in the config file).
But when I try 0.02, I don't get any correct alignment and the result is unusable. I tried to change different parameters like increasing preference loop registration but I can't get any result. 
What are the parameters I can change in the config (or the code)  to get a result ? I would like to be able to work with 0.02 and 0.01 voxel resolution (which is the theoretical resolution realsense sensor can achieve). Then how can I do that ?

**Comment by argosvr** [comment]
not.. I'm not speaking about tsdf_cubic_size (I know how I can get better reconstruction using that).. and the name comes from the ReconstructionSystem I'm using straight away which is the batch process given byt th open3d team. I'm speaking about voxel_size : from 0.05 to 0.03 I can tell you that the results are very very different.
And the realsense is noisy when you use them out of the box. But with the right light and the right parameters, the results are surprising good.
Then I maintain my question which is really about alignment and registration. Why does it work with 0.05,0.04,0.03 voxel_size and not with 0.02 ? I had to change option(WITH_OPENMP               "Use OpenMP multi-threading"               ON) to OFF because even with the last version of open3d, the examples were not giving expected results. But I don't see what are the parameters I can change to make it work at 0.02 voxel_size.

**Comment by theNded** [comment]
That's probably because the point cloud is too dense at the most coarse scale such that the registration goes to local optimal. 

See this [line](https://github.com/intel-isl/Open3D/blob/master/examples/Python/ReconstructionSystem/refine_registration.py#L98): now multi-scale ICP is performed on point clouds downsampled with voxel resolution [0.02, 0.01, 0.005], which will only reduce the point cloud size a little bit.

My suggestion is to keep the most coarse voxel resolution 0.05 to allow a higher convergence rate. If you want a better registration at a finer scale, I would suggest to change this line to something like
`[voxel_size, voxel_size/2.0, voxel_size/4.0, voxel_size/8.0], [50, 30, 14, 10],` (haven't tested, but it should work).

@syncle Should we tune the [code](https://github.com/intel-isl/Open3D/blob/master/examples/Python/ReconstructionSystem/refine_registration.py#L50) a little bit, so that when the voxel_size for downsampling is smaller than grid voxel size, we use the original point cloud instead of downsampling? This might improve the finest registration a little bit.

**Comment by argosvr** [comment]
thank you... I will try this.
After reading this issue - https://github.com/intel-isl/Open3D/issues/797 -and having very big questions about the registration process, I discovered that I was unable to register properly the Standford Burghers example. Then I rebuild from source using in cmakelist option (WITH_OPENMP  "Use OpenMP multi-threading" OFF).
Then (after a lot of problems because your conda script create a py36 env !) I was able to get a proper registration for the Standford Burghers example.
I had to reinstall totally my computer to get this work !
now, I will test your solution.. thanks.
But really with proper parameters and light (wich is very very important) you get very low loise even at 0.02 with the dr415 and the last firmware.

**Comment by argosvr** [comment]
at 0.2, the solution you gave me ([voxel_size, voxel_size/2.0, voxel_size/4.0, voxel_size/8.0], [50, 30, 14, 10]) worked very well and I can get a very good point cloud.
Because the Dr400 is able to get to 0.01, I tried it also...

**Comment by argosvr** [comment]
no  idea to make it work at 0.01 ???

**Comment by argosvr** [comment]
ok... no answer.. you don't like Intel cameras...

**Comment by theNded** [comment]
Sensor accuracy may provide clues for tuning parameters for registration or integration, but they are not neccessarily the same. For instance, registering point clouds is finding out the best possible transformation between two point sets with noise and partial overlap. The inputs are not the denser the better, otherwise the registration algorithm is likely to converge to the local minima. **A sensor can achieve 0.01 accuracy does not mean it is the best solution to register them starting from 0.01 voxel size.**

As I have mentioned, `voxel_size` defines the **coarsest** resolution for registration. You need to make sure the **coarsest resolution is large enough**, in order to assure a larger probability to converge to the global optimal. The usual practice is to start with a large number, and shrink it iteratively.  Based on this, by default we start from 0.05, and I have suggested to start from 0.05 with more iterations in my previous comments. 

If you insist on registering at the finest scale, just start with the default `voxel_size=0.05`, and do as many downsamplings as you like to shrink `voxel_size: [0.05, 0.025, 0.0125, 0.00625, ......]`. This is the configuration that is more likely to work. 

**More comments on your comments:**
We don't have preference on cameras. Instead, we try to find out the optimial configuration that generally works for all sensors. It may happen, due to different sensor properties, that this certain configuration does not work as good as expected. But the overall practice is to start from the existing tuned parameters, as they are based on our experience on various data. Please be sure to understand the roles the parameters play when you tun the parameters based your own understanding.

We try our best to solve as many issues as we can. Please be patient when you wait for a reply, and please make your questions more intepretable, see the [issue template](https://github.com/intel-isl/Open3D/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by robot-mh** [comment]
> I guess the naming is a little bit misleading. `voxel_size` is only used for registration and does not affect reconstruction resolution. What takes effect is `tsdf_cubic_size = 3.0`: the real voxel size used for reconstruction is `tsdf_cube_size / 512 = 0.0058`, which is already small enough.
> 
> Intel RealSense is noisy. If you want high quality body scans, I would suggest using StructureSensor or AzureKinect.

Intel RealSense is noisy, haha, open3D is also released by Intel.
