### ISSUE TITLE
compute_transformation

### ISSUE THREAD

**Issue by valvador92** [intel-isl/Open3D#1303]
Hi!

I would like to know what are the details of the calculation of the function 'compute_transformation' from the class 'open3d.registration.TransformationEstimation'.
This function is used in your example 'interactive_visualization.py'.

Thank you in advance

**Comment by argosvr** [comment]
same question.. then following the topic.

**Comment by valvador92** [comment]
Hi!
@argosvr  Do you have an answer to this question?

Are you using single value decomposition? Could you just tell me the name of the implemented method?

Thank you!

**Comment by griegler** [comment]
@syncle can you give some details?

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.
