### ISSUE TITLE
Can ICP limit the rotation between two point clouds?

### ISSUE THREAD

**Issue by fersolerv** [intel-isl/Open3D#1310]
I have two point clouds and the final rotation is about 90 degrees using ICP. These point clouds share some features and there is not need to use local or global feature extraction since they are close enough.

Is there a way to limit maximum rotation between two points using ICP?

**Comment by argosvr** [comment]
same question.. knowing the orientation of the camera, can we limit the rotation ?

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.
