### ISSUE TITLE
After using TSDF integrate, some points disappeared and holes were created

### ISSUE THREAD

**Issue by MaxChanger** [intel-isl/Open3D#1311]
I use my own dataset to test. As shown in this screenshot, on the left I convert rgbd image from all frames into point clouds and then add them together use the pose of `scene/refined_registration_optimized.json` and `fragments/fragment_optimized_%03d.json`, on the right I use Reconstruction System, `--integrate`, using ScalableTSDFVolume for integrate.

1. I don’t know why the point clouds in the blue box has disappeared. Originally the wall and the table were squatting, but after TSDF integrating, a big hole was created.

2. In addition, why is the grid in the green circle produced?

![Selection_036](https://user-images.githubusercontent.com/35401968/68584527-ca23e680-04ba-11ea-8e08-d3085af84b05.png)

**Comment by MaxChanger** [comment]
According to my test, after adding fragments_009 and fragments_010 to integrate, the result of scene is getting worse and worse.

**So it's related to the probability of a point in a voexl?**

![Selection_037](https://user-images.githubusercontent.com/35401968/68588903-95695c80-04c5-11ea-9982-1d0cb380464a.png)

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by MaxChanger** [comment]
Thanks. @germanros1987
