### ISSUE TITLE
 PoseGraph read JSON failed

### ISSUE THREAD

**Issue by zhangbeile** [intel-isl/Open3D#1349]
Dear 
   I use my own datasets from Iphone to get depth and color  but when I run the ReconstructionSystem they show PoseGraph read JSON failed: empty edges I don't know how to deal with

**Comment by syncle** [comment]
Literally, the pose graph seems empty. Could you tell what is your use case?

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by whubaichuan** [comment]
@syncle Do you only have one fragment?

**Comment by theNded** [comment]
Empty pose graph can be caused by the failure of odometry or registration. We will provide more debug info and tools in the next release. Closed for now.
