### ISSUE TITLE
How to set camera origin when viewing point cloud for video?

### ISSUE THREAD

**Issue by aj96** [intel-isl/Open3D#1376]
I'd like to make a video of point clouds using open3d, but the point cloud always moves around quite a bit. I fixed the height and width of the visualizer and the camera intrinsics and extrinsics, but it still seems to be moving around a bit too much. Are there any other properties I should be aware of for setting a constant camera origin?

**Comment by sammo2828** [comment]
Currently, when `add_geometry` is called, the viewpoint is reset based on the new bounding box.

Just merged is a new parameter `add_geometry(mypcd, reset_bounding_box=False)` which should stop the camera from moving around. https://github.com/intel-isl/Open3D/pull/1315

Youll have to build from source or wait until the next release.

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.
