### ISSUE TITLE
VoxelGrid.carve_depth_map incorrectly states that non visible voxels are not carved.

### ISSUE THREAD

**Issue by jkerfs** [intel-isl/Open3D#1441]
From the documenation for VoxelGrid.carve_depth_map:

> The point is not carved if none of the boundary points of the voxel projects to a valid image location.

However, the implementation does carve voxels when no points project into the image:
https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Geometry/VoxelGrid.cpp#L288-L309

The question is which behavior is desired.  I'm in favor of doing what the documentation says and not carving voxels if they do not project into the image.  If other agree with that, I can fix the function to adhere to that contract.

**Comment by griegler** [comment]
Yes, seems to be right, same for `CarveSilhouette`. The problem is with voxels that do not project into any image/valid image region. Ideally, we would have a function argument that let the user choose what to do in this case, i.e., carve or not carve. 
Would be great, if you could provide a PR for that!
