### ISSUE TITLE
error library windows 

### ISSUE THREAD

**Issue by scizors** [intel-isl/Open3D#1452]
open 3D widows error 
i installed using anaconda 
windows 
link:https://anaconda.org/open3d-admin/open3d

   from .open3d import * # py2 py3 compatible

ImportError: DLL load failed: The specified module could not be found.

**Comment by xiaohulihutu** [comment]
I am having the same issue. I tried on python 2.7 and 3.7 with VSCode and both had same issue. I can successfully use open3d-python 0.7.0.0 but cannot use the latest ver.

**Comment by yxlao** [comment]
Install `open3d` instead of `open3d-python`. I tested Open3D 0.9.0 pip and Conda installation under Windows 10 64-bit with python3.7 and they're all working for me.

Here's the full terminal recording for pip install:
https://terminalizer.com/view/fcc321e93273

Here's the full terminal recording for conda install:
https://terminalizer.com/view/0c3811b03274

Please try with the exact same command (including creating a fresh environment and activating it), and see if the problem still exists. Please feel free to reopen the issue.
