### ISSUE TITLE
How to you position camera and look at certain location in Open3D?

### ISSUE THREAD

**Issue by nickponline** [intel-isl/Open3D#1483]
How do you position the camera in the scene and point it towards a specific location? Is this possible in Open3D?

**Comment by radarAaron** [comment]
To set the initial viewing position of a scene do the following:

1. Run the visualizer and position the model using mouse/keyboard.
2. Once you are happy with this press the 'p' key. This will create a ScreenCamera_xxxx.json file which contains the relevant information.
3. Then add this to your code:
```
ctr = vis.get_view_control()
parameters = o3d.io.read_pinhole_camera_parameters("ScreenCamera_xxxx.json")
ctr.convert_from_pinhole_camera_parameters(parameters)
```

**Comment by jpouderoux** [comment]
@radarAaron What you write is interesting but it don't think it answers the question of @nickponline, which IMHO is, how to, programmatically, set the camera position and direction?

**Comment by karthikey97** [comment]
You might be able to do so by manually setting the camera parameters using the following function.

```python
open3d.visualization.ViewControl.convert_from_pinhole_camera_parameters(open3d.camera.PinholeCameraParameters: cameraParam)
```
You can create a cameraParam variable by using the default intrinsic param and constructing your own extrinsic matrix. You might try something like this:

```python
ctr = visualizer.get_view_control()

#This line will obtain the default camera parameters .
camera_params = ctr.convert_to_pinhole_camera_parameters() 
``` 
camera_params will contain the following properties:
1. camera_params.intrinsic (an object of PinholeCameraIntrinsic class that specifies properties like the focal length of the camera, width and height of the image etc.)
2. camera_params.extrinsic (a 4x4 numy matrix that specifies the translation and rotation with respect to the world frame)
 
Next you can create your own extrinsic matrix using your desired translation and rotation with respect to the global origin and provide it to the view control object like so:

```python
camera_params.extrinsic = # your desired matrix
# leaving camera intrinsics untouched
ctr.convert_from_pinhole_camera_parameters(camera_params)
```

**Comment by saprrow** [comment]
> To set the initial viewing position of a scene do the following:
> 
> 1. Run the visualizer and position the model using mouse/keyboard.
> 2. Once you are happy with this press the 'p' key. This will create a ScreenCamera_xxxx.json file which contains the relevant information.
> 3. Then add this to your code:
> 
> ```
> ctr = vis.get_view_control()
> parameters = o3d.io.read_pinhole_camera_parameters("ScreenCamera_xxxx.json")
> ctr.convert_from_pinhole_camera_parameters(parameters)
> ```

you saved me, bro

**Comment by pjbaron** [comment]
I'm attempting to modify the visualize_model.py script provided in Colmap, to draw the point cloud viewed from the cameras recovered from the images. To test, I'd like to be able to overlay a circle on the input images for each point in the point cloud to show what feature was matched.

My problem is that I cannot move the open3d camera.

I tried the solution from @karthikey97 but all of the different cameras show the same view, even when I manually hack the 't' translation vector.

I've never used python before so I'm jumping in well over my head, but if anyone can spot my mistake(s) I'd appreciate the help!

`# Copyright (c) 2023, ETH Zurich and UNC Chapel Hill.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#     * Neither the name of ETH Zurich and UNC Chapel Hill nor the names of
#       its contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import argparse
import numpy as np
import open3d

from read_write_model import read_model, write_model, qvec2rotmat, rotmat2qvec


class Model:
    def __init__(self):
        self.cameras = []
        self.images = []
        self.points3D = []
        self.__camera_vis = None

    def read_model(self, path, ext=""):
        self.cameras, self.images, self.points3D = read_model(path, ext)

    def point_cloud(self, min_track_len=3, remove_statistical_outlier=True):
        pcd = open3d.geometry.PointCloud()

        xyz = []
        rgb = []
        for point3D in self.points3D.values():
            track_len = len(point3D.point2D_idxs)
            if track_len < min_track_len:
                continue
            xyz.append(point3D.xyz)
            rgb.append(point3D.rgb / 255)

        pcd.points = open3d.utility.Vector3dVector(xyz)
        pcd.colors = open3d.utility.Vector3dVector(rgb)

        # remove obvious outliers
        if remove_statistical_outlier:
            [pcd, _] = pcd.remove_statistical_outlier(
                nb_neighbors=20, std_ratio=2.0
            )
        return pcd

    def create_camera_window(self, cam):
        self.__camera_vis = open3d.visualization.Visualizer()
        self.__camera_vis.create_window(window_name="Camera View", width=cam.width, height=cam.height)

    def display_camera_view(self, image_id, pcd):
        img = self.images[image_id]
        cam = self.cameras[img.camera_id]

        if self.__camera_vis is None:
            self.create_camera_window(cam)

        # Extract camera parameters
        R = qvec2rotmat(img.qvec)
        t = img.tvec
        #t[1] = -10.0    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< debug test, image 11 camera is at -3.xxx
        t = -R.T @ t
        R = R.T

        if cam.model in ("SIMPLE_PINHOLE", "SIMPLE_RADIAL", "RADIAL"):
            fx = fy = cam.params[0]
            cx = cam.params[1]
            cy = cam.params[2]
        elif cam.model in ("PINHOLE", "OPENCV", "OPENCV_FISHEYE", "FULL_OPENCV"):
            fx = cam.params[0]
            fy = cam.params[1]
            cx = cam.params[2]
            cy = cam.params[3]
        else:
            raise Exception("Camera model not supported")

        K = np.identity(3)
        K[0, 0] = fx
        K[1, 1] = fy
        K[0, 2] = cx
        K[1, 2] = cy

        # Set the camera parameters based on translation and rotation matrices
        extrinsic = np.eye(4)
        extrinsic[:3, :3] = R
        extrinsic[:3, 3] = t.flatten()
        
        intrinsic = open3d.camera.PinholeCameraIntrinsic()
        intrinsic.set_intrinsics(cam.width, cam.height, fx, fy, cx, cy)
        
        # Obtain the default camera parameters
        camera_params = self.__camera_vis.get_view_control().convert_to_pinhole_camera_parameters() 
        #camera_params = open3d.camera.PinholeCameraParameters()
        camera_params.intrinsic = intrinsic
        camera_params.extrinsic = extrinsic

        # Set the camera parameters
        self.__camera_vis.get_view_control().convert_from_pinhole_camera_parameters(camera_params, True)

        # display the point cloud
        self.__camera_vis.add_geometry(pcd)

        self.__camera_vis.poll_events()
        self.__camera_vis.update_renderer()

    def show_camera_view(self):
        if self.__camera_vis is not None:
            #camera_control = self.__camera_vis.get_view_control()
            #params = camera_control.convert_to_pinhole_camera_parameters()
            ## Extract the camera position from the extrinsic matrix
            #camera_position = params.extrinsic[:3, 3]
            #print("Camera Position:", camera_position)

            self.__camera_vis.run()
            
            #params = camera_control.convert_to_pinhole_camera_parameters()
            ## Extract the camera position from the extrinsic matrix
            #camera_position = params.extrinsic[:3, 3]
            #print("Camera Position:", camera_position)
            
            self.__camera_vis.destroy_window()

# class Model end


def parse_args():
    parser = argparse.ArgumentParser(
        description="Visualize COLMAP binary and text models"
    )
    parser.add_argument(
        "--input_model", required=True, help="path to input model folder"
    )
    parser.add_argument(
        "--input_format",
        choices=[".bin", ".txt"],
        help="input model format",
        default="",
    )
    args = parser.parse_args()
    return args

def main():
    args = parse_args()

    model = Model()
    model.read_model(args.input_model, ext=args.input_format)

    with open("world_cameras.txt", "w") as f:
        print("num_cameras:", len(model.cameras), file=f)
        print("num_images:", len(model.images), file=f)
        print("num_points3D:", len(model.points3D), file=f)

    # Display camera view for image_id
    model.display_camera_view(image_id=11, pcd=model.point_cloud())
    # Show the camera view window and run it
    model.show_camera_view()

if __name__ == "__main__":
    main()
`

**Comment by Petros626** [comment]
-- Mouse view control --
  Left button + drag         : Rotate.
  Ctrl + left button + drag  : Translate.
  Wheel button + drag        : Translate.
  Shift + left button + drag : Roll.
  Wheel                      : Zoom in/out.

-- Keyboard view control --
  [/]          : Increase/decrease field of view.
  R            : Reset view point.
  Ctrl/Cmd + C : Copy current view status into the clipboard.
  Ctrl/Cmd + V : Paste view status from clipboard.

-- General control --
  Q, Esc       : Exit window.
  H            : Print help message.
  P, PrtScn    : Take a screen capture.
  D            : Take a depth capture.
  O            : Take a capture of current rendering settings.
