### ISSUE TITLE
Kinect Azure extrinsic matrix from the IR to RGB camera in python API

### ISSUE THREAD

**Issue by sp-creol** [intel-isl/Open3D#1491]
How to find the rotation-translation matrix from the IR camera to RGB camera in python API? I think this information should be stored in MKV metadata, since unaligned depth and RGB frames can be aligned using MKVreader. How can I find this information?

**Comment by syncle** [comment]
It is possible, but I think that functionality is not exposed in Python API. I bet it is intended to make API simple (don't have to worry about alignment issue) and to fully utilize factory calibration parameters.

FYI, I have traced Kinect Azure API a bit.
https://github.com/intel-isl/Open3D/blob/661a9a197135389272c1227d1abe6a201abd2a8d/src/Open3D/IO/Sensor/AzureKinect/MKVReader.cpp#L97
It reads camera intrinsic from k4a metadata and utilized to align color and depth images
https://github.com/intel-isl/Open3D/blob/661a9a197135389272c1227d1abe6a201abd2a8d/src/Open3D/IO/Sensor/AzureKinect/MKVReader.cpp#L174-L176
You may hijack the ``transformation_``here.

Actually, you don't have to worry about this, because we are providing an option ``self.align_depth_to_color`` in our Python API. This option **will automatically align color and depth image domain.**
https://github.com/intel-isl/Open3D/blob/44a35978e78cf68a8368b90b173927ff0e0ef960/examples/Python/ReconstructionSystem/sensors/azure_kinect_viewer.py#L34

**Comment by sp-creol** [comment]
Thanks, I will give it a try.
