### ISSUE TITLE
Separating Patented and Non-Patented Code

### ISSUE THREAD

**Issue by HSarham** [intel-isl/Open3D#1559]
The function PointCloud::HiddenPointRemoval seems to be patented:
https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Software/HDR/HDR.html

It would be nice to separate the patented and non-patented code for example similar to OpenCV where patented code (e.g. SIFT) is in a "non-free" folder.

**Comment by germanros1987** [comment]
Hi,

I don't think this is actually doable. The case of SIFT in OpenCV was very special since the patent of SIFT was very well known and advertised. In our context, it would be hard to launch frequent patent searches to make this distinction. 

We are very careful with the licenses of different implementations, but going all the way to check the possible patents and their background IP should be the work of your legal team.

**Comment by HSarham** [comment]
Well, in this case it is stated right in the paper that it is patent pending. However you might be right. It was just a suggestion.
