### ISSUE TITLE
Pointcloud 3D model fitting

### ISSUE THREAD

**Issue by aycameric** [intel-isl/Open3D#1567]
Hello,

I am collecting a pointcloud of a scene with rc visard from roboception. And I want to fit a 3D CAD model of an object to the object in the scene. First I do fast global registration and then ICP (point to point). However, I don't get good results. The model is rotated and doesn't fit exactly on the object. Do you have suggestions what might be the issue and how I can solve it? Thank you.

**Comment by syncle** [comment]
ICP requires good initialization, and FGR requires good geometric features. Consider these properties when designing your approach. If the CAD model and real data shows inconsistency Consider this example - CAD model is clean mesh, but the real data is quite noisy. FGR will not work out-of-the-box because FPFH won't work well for matching.
