### ISSUE TITLE
Question: Images license

### ISSUE THREAD

**Issue by mashalahmad** [intel-isl/Open3D#1639]
Hi
Im using some of images of 3d Model from the open3D examples (fragment.ply)
My question is that are these images under MIT license too?

**Comment by theNded** [comment]
@qianyizh

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by germanros1987** [comment]
Sure.
