### ISSUE TITLE
Rotate coordinate frames around origin, not center

### ISSUE THREAD

**Issue by AlfTetzlaff** [intel-isl/Open3D#1745]
**Is your feature request related to a problem? Please describe.**
When calling rotate() on a coordinate frame it does not rotate around the origin (where the arrows meet) but instead around the center. This may be stringent behaviour and I respect if you leave it like that, but for coordinate frames this is irritating and annoying.

**Comment by griegler** [comment]
The problem is that `center` of all triangle meshes is just the mean of the vertices. I can imagine that it is annoying in this specific case. We could add add an additional parameter to `rotate` where the user might be able to specify a custom rotation center. @AlfTetzlaff @yxlao what do you think about this, or do you have other suggestions?

**Comment by AlfTetzlaff** [comment]
This sounds like a valid solution to me, as I could then simply rotate around the specified origin.
