### ISSUE TITLE
how can I get camera intrinsic ?

### ISSUE THREAD

**Issue by qiyueliao** [intel-isl/Open3D#1847]
I want to use
"pinhole_camera_intrinsic = o3d.io.read_pinhole_camera_intrinsic(config["path_intrinsic"])"
and
"o3d.camera.PinholeCameraIntrinsic.set_intrinsics(640,480,525.0,525.0,319.5,239.5)"
to get camera intrinsic, but both are wrong.
My config.json is:
{
"path_intrinsic": "[[525.0,0,319.5][0,525.0,239.5][0,0,1.0]]"
}
Thank you very much!

**Comment by SebastianGrans** [comment]
You need to provide more detail of what is wrong. It seems to work just fine when I try it. 

```python 
> phc = o3d.camera.PinholeCameraIntrinsic()
> phc.set_intrinsics(640, 480, 525.0, 525.0, 319.5, 239.5)
> phc.intrinsic_matrix
array([[525. ,   0. , 319.5],
       [  0. , 525. , 239.5],
       [  0. ,   0. ,   1. ]])
```

**Comment by qiyueliao** [comment]
I want to use two way to get the camera intrinsic,.The first question is: 
test.py
x=o3d.camera.PinholeCameraIntrinsic.set_intrinsics(640,480,525.0,525.0,319.5,239.5)
print(x.intrinsic_matrix)
but it run wrong, and here is the picture of wrong
![image](https://user-images.githubusercontent.com/42409750/82540810-147cd300-9b82-11ea-8dcc-26a83ef357b4.png)
The sencond question is I want to get the camera intrinsic from config.json.
test.py
pinhole_camera_intrinsic = o3d.io.read_pinhole_camera_intrinsic(config["path_intrinsic"])
config.json
{
"path_intrinsic": ""
}
how can I write the "path_intrinsic", is it a path to some other file include the camera intrinsic? If so, then how can I write this file,  is it a .txt file or others?
Thank you for your help!

**Comment by SebastianGrans** [comment]
It's because you are using it wrong. You are trying to invoke `set_intrinsics()` as a static function. But `set_intrinsic()` is supposed to be invoked on instances of the class. When you use it as a static function, there is no `self` and then you are trying to set `self` to the `int` value 640. Hence the error.

I believe this is what you actually want:
```python
pinholeCamera = o3d.camera.PinholeCameraIntrinsic(640, 480, 525.0, 525.0, 319.5, 239.5)
```
It is the third constructor in the [documentation](http://www.open3d.org/docs/release/python_api/open3d.camera.PinholeCameraIntrinsic.html#open3d.camera.PinholeCameraIntrinsic).

The format of the JSON file isn't explicitly documented, but when I used the `write_pinhole_camera_intrinsics('file.json', pinholeCameraInstance)` function the file has the following structure: 

```json
{
	"height" : 480,
	"intrinsic_matrix" : [ 525.0, 0.0, 0.0, 0.0, 525.0, 0.0, 319.5, 239.5, 1.0 ],
	"width" : 640
}
```

Which could subsequently be loaded using: 

```python
pinholeCamera = o3d.io.read_pinhole_camera_intrinsic('file.json')
```

**Comment by qiyueliao** [comment]
Thank you very much! It work well.
