### ISSUE TITLE
Open3D viewer app looks fantastic, but where to find the demo code? 

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#1890]
Hello, 

Open3D viewer app looks fantastic, but where to find the demo code? The link given seems broken?

Here is your link 
https://github.com/intel-isl/Open3D/releases/download/v0.10.0/Open3DApp-0.10.0-macosx-10_14.zip

Is the demo in Python and non-platform dependent?

Thank you!

**Comment by Dustinpro** [comment]
The same issue. It seems they deleted it from this repo.

**Comment by prewettg** [comment]
The GUI does not have Python bindings in 0.10.0, that is still in development and scheduled for 0.11.0. If you are using C++, you can look at src/Open3D/Visualization/Visualizer/GuiVisualizer.cpp for an example of how to use the GUI. The GUI uses OpenGL and Dear ImGUI, so it is cross-platform, although due to time constraints and build issues we only support macOS and Linux in 0.10.0. Windows support is also scheduled for 0.11.0.

I believe that a new 0.10.0.1 release supersedes the link you have, please check the Releases section for an updated link.

**Comment by griegler** [comment]
#2113 implemented the bindings.
