### ISSUE TITLE
Labeling information is missing when the pcd file is read

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [intel-isl/Open3D#1894]
Labeling information is missing when the pcd file is read.  

When we load a file from 3D dataset like shapenet, we have the xyzrgb and lable information in it, when we read the same with open3d we loss the label information from it. I have been using a semantic segmentation editor [https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor] for point cloud part segmentation and have been able to view the segmented pcd data in cloud compare [https://www.danielgm.net/cc/] but when I read the pcd with open3d I do not get the label information in it.  

I am looking out for the solution where we can read the pcd file with segmented information and process it [ex- downsample], it will be good to have a custom output format [save pcd] as well which can be in synch with the 3D datasets like shapenet, etc. 

Currently looking at point cloud library if there are any solutions for this.

**Comment by ShettyHarapanahalli** [comment]
I have exported the pcd points to numpy, using the below function 

np.asarray(pcd_load.points)  

I get only 3 dimension data, that is x,y,z all other fields are missing [the RGB, object, label etc]

**Comment by farmakis** [comment]
pcd.points only contains the points.
the missing RGB values are stored in pcd.colors and the normals in pcd.normals. Note that color values are within 0-1 range which means R/255, G/255, B/255.
A trick to solve your problem is to assign random RGB values to the scalar field containing your segments in CloudCompare, save the point cloud as .pcd file, read it in Open3D and use open3d.viusalization.draw_geometries([pcd]). You should be able to see the segments colored with different colors.
