### ISSUE TITLE
Installation using pipenv fails

### ISSUE THREAD

**Issue by jurc192** [intel-isl/Open3D#1899]
**Bug**
Trying to install latest Open3D (0.10.0.1 ) fails when using `pipenv`, with this output:
```
An error occurred while installing open3d==0.10.0.1 --hash=sha256:1eaf414d27067a993ffce1a5c3b9c2b9f261a3def2ae607eeba404ce2f13a1a1 --hash=sha256:44d23f799dd3defbd5202b233296a1cb04c4b962b3b0497773b7d0c2d73d8b50 --hash=sha256:a3f404b410092faf527c133dc2778ef8df457f0fa7d004778d07a21bbbf0b637 --hash=sha256:b83e76a77694fb9cf0ca5cb667046f9b77c0709f1752732b05c6fc4bee3960e1! Will try again.
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 1983, in do_install
[pipenv.exceptions.InstallError]:       do_init(
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 1246, in do_init
[pipenv.exceptions.InstallError]:       do_install_dependencies(
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 858, in do_install_dependencies
[pipenv.exceptions.InstallError]:       batch_install(
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: []
[pipenv.exceptions.InstallError]: ['ERROR: Could not find a version that satisfies the requirement open3d==0.10.0.1 (from -r /tmp/pipenv-w6psd9of-requirements/pipenv-dove0wmu-requirement.txt (line 1)) (from versions: 0.8.0.0, 0.9.0.0, 0.10.0.0)', 'ERROR: No matching distribution found for open3d==0.10.0.1 (from -r /tmp/pipenv-w6psd9of-requirements/pipenv-dove0wmu-requirement.txt (line 1))']
ERROR: ERROR: Package installation failed...
``` 
However, installing the package using `pip --user install open3d` works fine.

**To Reproduce**
Assuming you have `pipenv` installed, create a new directory and execute `pipenv install open3d` inside it.

**Environment:**
- Operating system: Arch Linux, 5.6.14
- Python version: Python 3.8.3
- Open3D version: 0.10.0.1
- Is this remote workstation?: no
- How did you install Open3D?: pipenv

**Comment by DerPhysikeR** [comment]
Hi everybody, I don't think the issue mentioned above is something specific to pipenv, since I get the same error with poetry and even pip.
While `pip install open3d` works, `pip install open3d==0.10.0.1` does not.

```
pip install open3d==0.10.0.1
ERROR: Could not find a version that satisfies the requirement open3d==0.10.0.1 (from versions: 0.10.0.0)
ERROR: No matching distribution found for open3d==0.10.0.1
```

I may be wrong, but there is something strange going on with the version number. Here on github the most recent release is `0.10.0.0` while on pypi there is a version `0.10.0.1`.

While poetry and `pipenv` seem to find a version `0.10.0.1`, which they are then unable to install, because it apparently doesn't exist for some reason, `pip` defaults to `0.10.0.0` which works. If you force poetry to also install `0.10.0.0` instead, it works. I suspect the same is true for pipenv.

The tag for this issue should probably be changed from feature request to bug.

**Comment by yxlao** [comment]
Currently,
- `open3d==0.10.0.1` only works on Windows, at that's a small patch that we apply to `open3d==0.10.0.0` for Windows to fix some installation issues: https://pypi.org/project/open3d/0.10.0.1/#files
- `open3d==0.10.0.0` should be used for Linux: https://pypi.org/project/open3d/0.10.0.0/#files
