### ISSUE TITLE
Error compiling branch ml-module on windows.

### ISSUE THREAD

**Issue by FlorentGuinier** [intel-isl/Open3D#1973]
Hey!

When compiling Open3d with ML module on windows (with BUILD_GLFW=ON to avoid problen with GLFW lib) I got a compilation error in regard to tensorflow.

clone the repo
$ git clone --recursive --branch ml-module https://github.com/intel-isl/Open3D.git
build it (with BUILD_GLFW=ON to avoid problen with GLFW lib)
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TENSORFLOW_OPS=ON -DBUILD_CUDA_MODULE=ON -DBUILD_GLFW=ON
-- New GUI is currently unsupported on Windows
<...>
-- Building library 3rdparty_poisson from source
CMake Error at src/Open3D/ML/CMakeLists.txt:2 (message):
`Building Tensorflow ops on Windows is currently not supported.`

That seems unexpected. Do you guys have an hint on what could be happening here?

Thanks!

Florent

**Expected behavior**
Successfull compilation

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.6
- Open3D version: see above latest from ml-module branch
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): Visual studio 15 2017 Win 64

Thanks!

**Comment by benjaminum** [comment]
Hi Florent,
we disable building the tensorflow ops for windows because we ran into some issues that we could not solve. For instance, Tensorflow 2.0 did not ship with the required libs and headers for building ops.
So far we did not have time to look into this again with a more recent version of TF.
If you want to give it a try you can simply remove this line https://github.com/intel-isl/Open3D/blob/5935abc12bf2228d5f0a034b4040f24f1c8cdd11/cpp/open3d/ml/CMakeLists.txt#L2
Any help for supporting windows is welcome.

**Comment by FlorentGuinier** [comment]
We just tried with TF 2.0, 2.1 and 2.2 and no luck (by removing the check as you suggested).

**Comment by FlorentGuinier** [comment]
In case it might help someone out there using WSL (windows subsystem for linux) can be considerered as a workaround atm.

**Comment by germanros1987** [comment]
It seems we just don't have support for ML in Windows, so I am closing this.
