### ISSUE TITLE
RuntimeError: [Open3D ERROR] [CreateCoordinateFrame] size <= 0

### ISSUE THREAD

**Issue by Jiayuan-Gu** [intel-isl/Open3D#1991]
**Describe the bug**
RuntimeError: [Open3D ERROR] [CreateCoordinateFrame] size <= 0

**To Reproduce**
A minimal example to reproduce

```python
import numpy as np
import open3d as o3d

points = np.zeros([100, 3])
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
geometries = [pcd]
o3d.visualization.draw_geometries(geometries)
```

**Expected behavior**
Render a single point in the scene

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.7
- Open3D version: 0.10.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
It seems to be reported by #1697 as well. I suspect it is caused by trying to infer a coordinate frame.

**Comment by germanros1987** [comment]
@theNded do you have the bandwidth to take a look?

**Comment by theNded** [comment]
This is a feature rather than a bug, because we require a [non-trivial bounding box](https://github.com/intel-isl/Open3D/blob/5935abc12bf2228d5f0a034b4040f24f1c8cdd11/cpp/open3d/geometry/TriangleMeshFactory.cpp) of the geometry to create a guidance coordinate frame (though not visible by default). 

However we may lift this strict constraint by adding a tiny number to 
['boundingbox.GetMaxExtent() * 0.2'](https://github.com/intel-isl/Open3D/blob/b58440d61b882a5d0849a329c08a6bd8b85e15ba/cpp/open3d/visualization/visualizer/Visualizer.cpp#L239
).

**Comment by trsarje** [comment]
I am facing the same issue. When I try to combine three-point cloud.
