### ISSUE TITLE
Callback function to get current cursor position in 3-space

### ISSUE THREAD

**Issue by ch-sa** [intel-isl/Open3D#2080]
**Is your feature request related to a problem? Please describe.**
I would like to implement an interactive visualization where the user can draw 3D-bounding boxes. This would require drawing a 2D-bounding box (currently possible) and then interactively extending the rectangle into the third dimension for creating a 3D-bounding box. This would require knowing the current position of the (pressed) cursor to give the user an updated view of the 3D-bounding box depth.

**Describe the solution you'd like**
A callback function similar to [`get_picked_points()`](http://www.open3d.org/docs/release/python_api/open3d.visualization.VisualizerWithEditing.html#open3d.visualization.VisualizerWithEditing.get_picked_points) which returns the current cursor position as an array [x,y,z] every t milliseconds.

**Describe alternatives you've considered**
The depth of the bounding box could also be taken from another user selected voxel, but this would not enable an interactive visualization of the 3D-bounding box dimensions.

**Additional context**
The current examples from the [interactive visualization tutorial](http://www.open3d.org/docs/release/tutorial/Advanced/interactive_visualization.html) so far always require closing and reopening the window (_e.g., cropping & manual registration_). So a side-question is if the current event-cycle of the `draw_geometries_with_*`-functions actually allows for interactive drawing (_i.e. adding new geometries based on user input_).

Thanks for any help and comments are appreciated.

**Comment by fabiopoiesi** [comment]
I was discussing with a colleague of mine, the exact same thing 2 hours ago ;-)

**Comment by griegler** [comment]
I am not 100% sure, but the new visualizer has more callback functionalities. @prewettg can you comment on this please.

**Comment by prewettg** [comment]
We are currently working on an improved GUI / visualizer framework which will be much nicer, but it does not have this feature on the schedule at the moment. However, you can use the camera matrix and the mouse position (relative to the 3D view rectangle) to calculate the direction of a ray coming from the viewing plane. One easy way would use the equivalent of gluUnProject, where x, y are the mouse coordinates, and then since you want a ray, simply use two different values for z. You won't be able to call gluUnProject, but the man page (or the Khronos documentation) will give the equation.
