### ISSUE TITLE
seg fault on all o3d.visualization.draw_geometries calls

### ISSUE THREAD

**Issue by esteimle** [intel-isl/Open3D#2109]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I built and installed from source to get around some missing method errors. I get farther now but when trying to run an example such as colored_pointcloud_registration I always get a seg fault. It happens in other examples as well.  I tried getting a stack trace but this is all it leaves behind.

        Signal: 11 (SEGV)
     Timestamp: Mon 2020-07-27 09:52:57 EDT (50min ago)
  Command Line: python colored_pointcloud_registration.py
    Executable: /home/xxx/anaconda3/bin/python3.7
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (xxx)
       Boot ID: a8556651baef4c2eb4e4590f1a31b755
    Machine ID: 69315d7c9e0c4a0392d72f5926824169
      Hostname: xxxx
       Storage: /var/lib/systemd/coredump/core.python.1000.a8556651baef4c2eb4e4590f1a31b755.9600.1595857977000000.lz4
       Message: Process 9600 (python) of user 1000 dumped core.

                Stack trace of thread 9600:
                #0  0x0000000000000000 n/a (n/a)

**To Reproduce**
run colored_pointclouds_registration in python

**Expected behavior**
no seg fault 

**Screenshots**

**Environment (please complete the following information):**

- Operating system: Ubuntu 19
- Python version: 3.7
- Open3D version: from source 7/25/2020
- Is this remote workstation?: no
- How did you install Open3D?: source

**Additional context**

**Comment by benjaminum** [comment]
Hi @esteimle , can you compile in Debug mode to get more information?

**Comment by femust** [comment]
i have also similar problem even with example cpp file PCDFileFormat.cpp and with pcd file from your tests

**Comment by benjaminum** [comment]
This is probably the same issue as in #2112 . Don't hesitate to reopen if there is new information, which suggests that this problem is different.

**Comment by zhaoyuanyuan2011** [comment]
Got seg fault again on all draw_geometries calls. This only happens when build from source. It won't happen with conda/pip3 install open3d and open3d-python, but conda/pip3 install results in missing packages of TetraMesh when trying to run o3d.geometry.TetraMesh.create_from_point_cloud(pcd).

Tried cmake -DENABLE_GUI=OFF .. in build/ but didn't work.

These happens when trying to run the surface reconstruction demos.
http://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html

**Environment (please complete the following information):**

Operating system: MacOS 10.15.7
Python version: 3.8.5
Open3D version: from source 10/21/2020
Is this remote workstation?: no
