### ISSUE TITLE
Unexpected behavior in get_picked_points()

### ISSUE THREAD

**Issue by rfc2119** [intel-isl/Open3D#2156]
## Description
`get_picked_points()` returns selected points inside a visualizer. It adds them one by one in a queue data structure. However, the points returned do not follow the exact same order I have chosen visually

**To Reproduce**

```python
In [87]: def welp(mesh, edit=False):
    ...:     vis = o3d.visualization.VisualizerWithVertexSelection() if not edit else o3d.visualization.VisualizerWithEdit
    ...: ing()
    ...:     vis.create_window()
    ...:     vis.add_geometry(mesh)
    ...:     vis.run()
    ...:     vis.destroy_window()
    ...:     return vis.get_picked_points()
    ...: 

In [88]: _tmp = welp(meshRawSorted)
[Open3D INFO] Clearing all points from selection.
[Open3D INFO] Adding point #24547 (-0.02, 17.46, 15.17) to selection.
[Open3D INFO] No point has been picked.
[Open3D INFO] Adding point #24153 (-0.02, 16.95, 15.38) to selection.
[Open3D INFO] Adding point #23101 (-0.02, 16.36, 15.35) to selection.

In [89]: for point in _tmp:
    ...:     print(f'#{point.index} ({point.coord})')
    ...: 
#23101 ([-0.02054    16.3606739  15.35050583])
#24547 ([-0.019383   17.46112251 15.1733942 ])
#24153 ([-0.018746   16.94936562 15.38034058])
```

## Expected behavior*
The indices should be returned in a queue-like order (so points number [23101, 24153, 24547] or the reverse)

- Operating system: debian10 (buster)
- Python version: 3.7
- Open3D version: 0.10.0 (current release in pypi as of today)
- How did you install Open3D?: pip

**Comment by rfc2119** [comment]
Hello again, thank you for adding the bug label. If you think this issue is trivial and is easy to fix, can you show me where to find the code for queuing the selected input ?

**Comment by prewettg** [comment]
Apologies for a late response. VisualizerWithVertexSelection allows users to select and unselect by rectangle, so for efficiency in determining if a point has already been selected we use a dictionary, rather than a list. Also, if you select by rectangle, the order those points should come in seems not well-defined. It looks like VisualizerWithEditing just appends the points to the list in the order they were picked, so if VisualizerWithEditing has the features you need, using that is probably the easiest solution. You can find the code for both of those in VisualizerWithVertexSelection.cpp and VisualizerWithEditing.cpp. In master they are in cpp/open3d/visualization/visualizer, although in 0.10 I think the structure may have been slightly different.

**Comment by Zenway-Wong** [comment]
@prewettg I just encounter this problem again (the returned points from **VisualizerWithVertexSelection** is not in the same order of selection). I changed to use **VisualizerWithEditing** but it seems that it can not be used to select mesh vertices...

Is it necessary to transform mesh into poindCloud first to use **VisualizerWithEditing**?

**Comment by x1y9** [comment]
I have this issue too.  The workaround is using a callback to get a ordered selection list

```
selected=[]
def sel_changed():
    if len(vis.get_picked_points()) == 0:
        selected.clear()
    else:    
        for p in vis.get_picked_points():
            if p.index not in selected:
                selected.append(p.index)
vis = o3d.visualization.VisualizerWithVertexSelection()
vis.register_selection_changed_callback(sel_changed)
```
