### ISSUE TITLE
PoseGraph read JSON failed: empty edges.

### ISSUE THREAD

**Issue by Anita1683147070** [intel-isl/Open3D#2222]
It works effectively with the bedroom sample data, but I'm trying the Reconstruction System with my own dataset, about 40 panoramas. I used the make_fragments.py script, and the color images are 32bit, depth images are 16bit (png), 4500*9000, they described a complete 600 square meter interior.
I get an error"**PoseGraph read JSON failed: empty edges**." when trying to **register**. Does open3d work with panoramas?  Or do I need to modify any parameters?

Thank you.

my camera.json
`{
        "width" : 9000,
        "height" : 4500,
        "intrinsic_matrix" :
        [
                512.0,
                0,
                0,
                0,
                525.0,
                0,
                319.5,
                239.5,
                1
        ]
}`
config.json
`{
    "name": "Open3D reconstruction tutorial http://open3d.org/docs/release/tutorial/ReconstructionSystem/system_overview.html",
    "path_dataset": "dataset/myDataset/",
    "path_intrinsic": "dataset/myDataset/camera.json",
    "max_depth": 3.0,
    "min_depth": 0.3,
    "n_frames_per_fragment": 100,
    "n_keyframes_per_n_frame": 5,
    "voxel_size": 0.05,
    "max_depth_diff": 0.07,
    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,
    "tsdf_cubic_size": 3.0,
    "icp_method": "color",
    "global_registration": "ransac",
    "python_multi_threading": true
}`

**Comment by theNded** [comment]
We only support pinhole camera model, so combining the pinhole intrinsic matrix with panorama input will result in wrong 3d point clouds. Please try to consider converting the panoramas to pinhole models.

**Comment by xsertx** [comment]
Hi, I have a problem. I work with rgbd panoramas. So since open3d supports only pinhole camera model, I converted panoramas to perspective views (w=640, h=480). However, when i tried to [create a pcld from rgbd](http://www.open3d.org/docs/latest/tutorial/Basic/rgbd_image.html) the result looks wrong (distorted). It feels like my camera intrinsics are wrong, but i'm not sure.

PinholeCameraIntrinsic with width = 640 and height = 480.
Access intrinsics with intrinsic_matrix.
[[640.   0. 320.]
 [  0. 480. 240.]
 [  0.   0.   1.]]

Could you help me with my problem ? 

<img width="784" alt="Screen Shot 2021-02-16 at 4 34 12 PM" src="https://user-images.githubusercontent.com/29440138/108031823-d828c580-7074-11eb-867d-4a74fc6f048f.png">
