### ISSUE TITLE
Using intel realsense T265 in the construction system to construct a posegraph (make fragments)

### ISSUE THREAD

**Issue by gftrobots** [intel-isl/Open3D#2234]
We are using the intel real sense T265 tracking camera for localization and are impressed by its accuracy.
Does it makes sense to use the odometry data from the T265 to construct the posegraph or is the precision / quality of Open3Ds own algorithms higher, than the precision of the T265?

**Comment by theNded** [comment]
Unfortunately T265 doesn't have depth sensing so Open3D's RGB-D pipeline is not a good fit. Please rely on T265's own SDK.

**Comment by SafariMonkey** [comment]
I'd like to point out that @gftrobots edited the question, clarifying that it is about using the T265 odometry with D435 depth images instead of relying on Open3D's own alignment. This clarification makes the original answer given by @theNded irrelevant, as depth frames are available from the D435.

I'm sure there are a number of us interested in using the T265+D435 for this purpose, so guidance on whether and how the T265 pose stream can/should be utilised would be appreciated.
