### ISSUE TITLE
Multi-processing with new GUI module

### ISSUE THREAD

**Issue by cygann** [intel-isl/Open3D#2300]
I have a process that is creating Open3D point cloud objects from numpy arrays, and I would like to use the new GUI module to visualize them as they're being created. I have tried to solve this myself, but was wondering if I could get some advice/pointers on accomplishing this. 

I noticed from the vis-gui.py example, `gui.Application.instance.run()` will run the event loop until the window is closed. I saw that this [python binding calls RunOneTick in a loop](https://github.com/intel-isl/Open3D/blob/master/cpp/pybind/visualization/gui/gui.cpp#L140), so I wrote my own python binding for this function (RunOneTick) in order to allow the python process running the visualization to dynamically update the scene's geometry.

Right now, I have two processes. Process 1 is constructing numpy array representations of new point clouds, and process 2 runs the following visualization loop:
```
        while True:
            # Processes one vizualizer event
            gui.Application.instance.run_one_tick() # This function is a python binding of RunOneTick

            # Check to see if there is anything new in the queue.
            if not self.publish_queue.empty():
                item = self.publish_queue.get()
                self.render_points(item)   # This function removes the current geometry and adds the new one in
```
Where `publish_queue` is a multiprocessing queue created in process 1.

My first solution was to have process 1 build a point cloud object and put it in the queue for process 2 to render. Unfortunately, since the Open3D point cloud geometry cannot be pickled, I can't send it over the multiprocessing queue. I next tried just placing the original numpy array in the queue and building a new point cloud object from it (In process 2) using the `o3d.utility.Vector3dVector` function, however for the point cloud size I'm working with, this function alone takes too much time (up to 0.75 seconds on my mac) to complete. This is functional, however the latency from `Vector3dVector` then blocks any actions on the GUI, which makes it pretty much unusable. 

I was wondering if anyone could give me some pointers on how I should proceed. Would it be doable to figure out how to make the point cloud geometry object pickle-able? Are there other multiprocessing tricks I should try to make this work? Is there functionality in the GUI module I don't know about that helps with accomplishing this? Any input would be appreciated. 

Thanks!

**Comment by prewettg** [comment]
It sounds like your problem is that everything is happening on the same thread, so if you load the geometry it prevents the UI from working and vice-versa. It sounds like what you want to do is have one thread read geometry (from a queue, from a file, over the network, wherever) and have the UI thread continue to operate, with the geometry thread posting the complete geometry back to the UI thread when finished, is that correct?

If so, you will want to update master from today, which has a change to gui.Application.run() that releases the GIL while we wait for events. This allows another Python thread (created from the `threading` module) to run. This thread can monitor the queue, load the geometry, and then call gui.Application.instance.post_to_main_thread() to post a Python function that adds/replaces the new geometry. The function must take no arguments and return no values, so you might want to pass in a nested function so that you can capture the geometry:
```
def loading_thread_main(...):
    ...
    geometry = load(...)

    def display():
        open3d_scene.add_geometry(name, geometry, material)

    gui.Application.instance.post_to_main_thread(display)
```

There is not a Python example illustrating this yet, but you can look at cpp/open3d/visualization/visualizer/GuiVisualizer.cpp, in GuiVisualizer::LoadGeometry() which does this process in C++. (Application::RunInThread() is a convenience function for C++, threads are a lot easier to create in Python.

While your use case should work, be aware that Python's GIL makes anything other than I/O effectively single-threaded.

**Comment by cygann** [comment]
Thank you for your response, this was super helpful.

**Comment by JeisonPham** [comment]
@cygann Would you be willing to post your code? I am having trouble managing two separate threads/processes.
