### ISSUE TITLE
MSB3073	error while installing 

### ISSUE THREAD

**Issue by rajanidulal** [intel-isl/Open3D#2316]
- Operating system: Windows 10 64-bit
- Language: C++
- Open3D version:
- Is this remote workstation?:  no
- How did you install Open3D?:  build from source
- CMake: 3.18.2
- IDE: Visual Studio 2019

I compiled from the source following instructions from here: http://www.open3d.org/docs/release/compilation.html#compilation. 

Got an MSB3073 error during installation. It says:  The command "setlocal"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	

![image](https://user-images.githubusercontent.com/56923694/92797599-d47f6d00-f377-11ea-91ed-4f44ff6924a6.png)

Also, is there any way to run this project in debug mode?

**Comment by yxlao** [comment]
Does it only happen in the install step? Was the compilation step working? 

A quick search shows that "Error MSB3073 is generally caused by an incorrect path in the command line". So possibly this is due to permission error (e.g. installing into system folders without using an administrator shell). If this is the case, we can specify a different `CMAKE_INSTALL_PREFIX` to point to somewhere in your `User` directory.

**Comment by rajanidulal** [comment]
Yes, it happened during the installation step. It was indeed the permission error and was solved when I ran my VS as an administrator. Thank you!

@yxlao Is there anyway to run this project in debug mode.

**Comment by yxlao** [comment]
Yes. If you do it in the terminal, it looks likes this:
```powershell
cmake --build . --config Debug --target ALL_BUILD
```
There should be an equivalent setting in VS Studio GUI to switch to debug mode.
