### ISSUE TITLE
Framework interoperability

### ISSUE THREAD

**Issue by Firefly35** [intel-isl/Open3D#245]
Hello, 
as we are using several frameworks, we expect to have some binding methods upon data structures. For instance, We'd expect the PointCloud class to have a wrapping constructor (such as the one provided in openCV for the cv:Mat) for performance reasons : no need to reallocate the datastructure. 
The wrapping constructor could accept a data array with offset, data ordering information for instance.

**Comment by qianyizh** [comment]
Is this request for the C++ interface or for the Python interface?

For the Python interface, I think it is already using the binding mechanism if you are using ``numpy.array``. See this for example:
http://www.open3d.org/docs/tutorial/Basic/working_with_numpy.html
Under the hood it implements the [pybind11 buffer protocol](http://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html), which provides fast direct access to the raw internal data representation.

For the C++ interface, I actually debated it back and forth. The main reason I decided not to use the binding mechanism is that C++ does not have a well defined ownership system. For example, a function constructs a buffer of data and wrap it into a ``three::PointCloud``, both the function and the PointCloud class can be the owner of the data. This adds confusion and risk of bugs and dangling pointers. On the other hand, copying (especially for a block of raw data) is not that bad in C++. I have done extensive testing. Copying only adds very small amount of running time.

I am open for discussion if there is a need to improve performance.

**Comment by Firefly35** [comment]
Sorry, I didn't see your answer at the time.
In fact, I thought of a similar mechanism that openCV provides with cv::Mat : it allows to bind(wrap) a buffer owned by the framework user under a cv::Mat. When the cv::Mat is initialised from the wrapping constructor, the cv::Mat class consider that it doesn't own the buffer, hence when the cv::Mat goes out of scope, the wrapped buffer is not deallocated.
I allows to have a memorypool of buffers recycled in the case of a video pipeline for instance, that are used and computed with OpenCV methods in an efficient way.
I thought IntelVCL could provide the same initialisation mechanism for the PointCloud class.

**Comment by qianyizh** [comment]
Yeah, I understand the mechanism of ``cv::Mat``. The reason I decided against it is that it exposes a risk that the buffer is released by the framework user while the binded ``cv::Mat`` is still being used. There is no way to prevent it mechanically - you are completely relying on developers to write the correct code. Otherwise, this will cause a memory access error, which IMO is a pretty ancient thing that should not exist in modern languages.

I looked for answers and got inspired by this long post: https://github.com/isocpp/CppCoreGuidelines

One idea I got from this post is that you can rely on memory copy - it is surprisingly fast on modern CPUs. Also modern computers have lots of memory so the redundancy is also less of an issue. I did tests myself. I compared smart pointers, self-maintained memory pools, and direct memory copy. The result surprised me. Memory copy is actually very fast. So I decided to use it instead of creating complication with bindings.

So far it seems to be working fine. If you have a specific use case in which you think memory copy impacts the performance a lot, do let me know and we may decide to build the binding mechanism. But so far I don't see a very strong need for it.

**Comment by sky3** [comment]
Hi,
first thanks for your time.
I guess the question generalize to many others frameworks.
Luckily, many open source communities are growing arround 3d reconstruction, slam, geometry and image manipulation framework. Something really cool is that all these frameworks perform really well on their problems and reach a significant milestone in term of quality.

Specific hardware are quite common to speedup some algorithms but  some framework API such as Halide, openVX emerged and can help to provide significant gap performance if the application is aiming to get real time performance.

Unfortunately, there is no real way to provide full interoperability between all these different frameworks and performance API without binding an existing buffer. For real time problem such as SLAM, duplicating the geometry to extend a point cloud  will cost some extra RAM.However, duplicating data structure and visibility relationship to perform a bundle ajustement can cost a lot if the data are not packed properly in memory.

**I am myself looking about this aspect to release delighting code from multiple views.
