### ISSUE TITLE
trying to build from source on a Jetson Xavier Agx still not working..

### ISSUE THREAD

**Issue by Fred3D-tech** [intel-isl/Open3D#2454]
Using the last Xavier Jetson and the last instructions from Open3D forum, still unable to build a working Open3D library... give us a clear solution, be serious!
https://github.com/intel-isl/Open3D/blob/master/.github/workflows/openblas.yml IS NOT WORKING.

**Comment by Fred3D-tech** [comment]
what is the correct procedure to use openblas.ylm? trying to build step by step, you get an error about open_blas variable not set..

**Comment by yxlao** [comment]
The `openblas.yml` is working since it is verified by the CI. Use it as a reference only since it also contains CI-specific scripts.

I recommend getting the lastest master and follow https://github.com/intel-isl/Open3D/blob/master/docs/arm.rst steps. Please post the full error message that you get if you encounter any.
