### ISSUE TITLE
Add matcaps for Open3D rendering?

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2546]
Hello, 

It looks that the [matcaps](https://github.com/nidorx/matcaps) rendering is very attractive. And it is also "cheap" to achieve.

Here is the [metcaps implementation](https://polyscope.run/py/features/materials/) in Polyscope. Another [good example](http://www.beautybuddyapp.com/examples/matcap.html) for point cloud.

May be it is interesting for Open3D developers to add?

Thank you!

![image](https://user-images.githubusercontent.com/59957922/97491262-2f8a1500-1962-11eb-90ce-026854f5bbba.png)

**Comment by 1939938853** [comment]
Hello,

OK, I just found that Open3D may already have a similar rendering effect as the metcaps.  See below, it is just a point cloud data with normal estimated. 

But it looks that the material "color coating" is sensitive to normal direction.  **Any way to make it insensitive to normal direction?** OrientNormals operation is very expensive!

Furthermore, must Open3D rendering module working together with the gui module? 

Thank you!

![image](https://user-images.githubusercontent.com/59957922/97621555-53615f80-1a23-11eb-8d54-030430eca6e7.png)

**Comment by prewettg** [comment]
We do not have any plans to add metcaps, because as you have already discovered, we already have full real-time physically-based rendering. Correct normals are required (that is, the normal should be pointing away from the surface) because that is how the shaders calculate how bright the pixel is.

I'm not entirely sure what you mean by "must the rendering module work with the gui module". Technically it is possible to use the rendering module without the GUI module (since that's what the GUI module has to do), but you'd be rewriting a lot of code. But perhaps I could answer your question better if you asked what you wanted to do directly.

**Comment by 1939938853** [comment]
Hello prewettg,

Thank you for your replay!

Because OrientNormals operation is a little bit "too expensive" to use for me,  20 thousands point takes ca 400 ms while normal estimation is only ca 20 ms, I  have to avoid using it. In this case maybe I need to set the same color for both normal direction (out-wards and in-wards) surfaces, i.e. set blue color for both sides of the above mentioned example. 

Is it possible?

**Comment by prewettg** [comment]
No, standard lighting requires that the normals be correct in order for the color to be correct.
