### ISSUE TITLE
how to visulize a real-time lidar pointcloud?

### ISSUE THREAD

**Issue by jiqirenno1** [intel-isl/Open3D#2560]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

i want to visualize the real-time  lidar pointcloud from robosense lidar. so I run the below c++ code, i saw the pointcloud, but i can not Zoom in/out the pointcloud by mouse wheel
```
       auto vis_ptr = std::make_shared<open3d::visualization::Visualizer>();
       vis_ptr->CreateVisualizerWindow();
        vis_ptr->ClearGeometries();
        vis_ptr->AddGeometry({cloud_ptr});
        vis_ptr->UpdateGeometry();
        vis_ptr->PollEvents();
        vis_ptr->UpdateRender();
```

**Comment by prewettg** [comment]
We are upgrading the Visualizer to use the new GUI which does support wheel (and trackpad) zoom. We won't be fixing any bugs in the old code, so I'm closing this. If your point cloud is stored in a file you can use the Open3D viewer app. You can load the file from the menu / dialog, or if you want a more scriptable interface, you can pass the path to the file to load, `path/to/Open3D path/to/point_clod`. Alternatively, since you're using C++ you can use the `GuiVisualizer` class that we used to build the Open3D viewer app, which uses the new GUI and does support wheel zoom.
```
#include "open3d/Open3D.h"
#include "open3d/visualization/visualizer/GuiVisualizer.h"

int main(int argc, char *argv[]) {
    auto &app = gui::Application::GetInstance();
    app.Initialize(argc, argv);

    auto cloud_sharedptr = GetMyPointCloud(...);
    std::vector<std::shared_ptr<const Geometry>> geom = { cloud_sharedptr };

    auto vis = std::make_shared<GuiVisualizer>(geom, "Open3D", WIDTH, HEIGHT);

    // alternatively you can use this if you point cloud is on disk
    // vis->LoadGeometry(path);

    gui::Application::GetInstance().AddWindow(vis);
    // when Run() ends, Filament will be stopped, so we can't be holding on
    // to any GUI objects.
    vis.reset();

    app.Run();
```
(I didn't compile that, but that should give you the general feeling. See `cpp/apps/Open3DViewer/Open3DView.cpp`.)  Note that the new GUI needs to be able to locate the `resources` directory, which is most easily done by putting the `resources` directory in the same directory as the executable.
