### ISSUE TITLE
Open3D coloring 3D point cloud using labels

### ISSUE THREAD

**Issue by edshkim98** [intel-isl/Open3D#2619]
Hi, I have 3D point cloud data to perform semantic segmentation which I am trying to visualize it using Open3D.
Unfortunately, it does not come with RGB colors but it has labelling for each point.
Most of the examples so far in open3D, people have used RGB colors to visualize it.
Is there anyway to visualize the point cloud in colors corresponding to the labels?
My data looks as follow:
points: (100000,3)
labels: (100000,) which looks like array([1, 1, 1, ..., 0, 0, 0])

Thank you.

**Comment by JordanMakesMaps** [comment]
So although you closed this issue, others might have the same question in the future. I'm working with PCD where there is just a single intensity value for each point (XYZI). Because O3D can only add RGB(?) I use a colormap from matplotlib.pyplot to create RGB values for each point's I value:

```python
    cm = get_cmap("afmhot")

    intensity = dataframe['I'].values
    intensity = np.array(intensity) / 255.0
    intensity = cm(intensity)[:, 0 : 3]
```
This then gets used as the PCD's color attribute.
