### ISSUE TITLE
GUI module: compatible with custom pyimgui codes? How to update images in ImageLabel dynamically?

### ISSUE THREAD

**Issue by Harry-Zhi** [intel-isl/Open3D#2784]
Hi,

I recently played with the python GUI module in open3d which looks great.

There are several questions when I want to achieve a pangolin-like GUi system with both image sequence and 3D mesh visualised.

1.The GUI module is based on ImGUI project, is it possible to write our own imgui/pyimgui codes to append the limited gui APIs currently? I tried to create a window using pyimgui and it does not seems to work properly with open3d gui window..Any tips for this?

2.The visualisation module looks good with relatively complete APIs while the GUI module looks very independent from the visuallisation module. Is this indendency aimed or are there any ways to shift visulisation tools to gui module?

3.Is the current GUI module capable of showing changing images or videos?
Currently it seems only alble to show a static icon and I did not find a way to replace the image later when other new image content coming. I am wondering if it is possible to show a ImageLable with changing images?

I found that the recent PR add mouse/key callback to SceneWidget of GUI , is mouse/key callback also applicable to general window of open3d gui since it is also required usually to have mouse interaction for ImageLables (e.g., get  pixel colour value from a mouse selected pixels).

**Comment by prewettg** [comment]
Using pyimgui is unlikely to work with Open3D's version. Pyimgui presumably includes a small library containing the ImGUI code, as does Open3D. ImGUI keeps a lot of hidden state (indexed on the object name), so you have two different copies of the library keeping two different sets of state.

The current visualization model uses raw OpenGL calls, which is simple but limited. We are in the process of replacing it, but you've come in while we're still mid-transition. However, we've recently added a new visualization module using the new UI and which combines most, if not all, of the aspects of the old visualizers (the functionality of the old visualizers was not composable, so some features were not available together with other features). This new visualization module can act as a draw_geometries() replacement, just change use `draw(...)` instead of draw_geometries. You can see the [examples/python/gui/draw.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py) example for samples of various features. Also, you can use the open3d.visualization.O3DVisualizer class directly if you wish as well (see [python/open3d/visualization/draw.py](https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py), which implements `draw()`, for sample usage). A similar C++ example is in the C++ examples. This new visualizer will be available in 0.13, or you can compile from source and try it now.

We added support for a background image in SceneWidget (technically, Open3DScene::SetBackground()) and it will be in 0.13, but we are still working on video support. You can call Open3DScene::SetBackground repeatedly, however, it will create a new texture in the Filament backend every time, and Filament can only create a fixed number of graphics items before it runs out of IDs internally and crashes. We are still working on using Filament's ability to replace the texture contents instead of creating an entirely new texture, but it is unlikely to make it in to 0.13.

What are looking to do with the ImageLabel? It was intended for use for icons, logos, displaying PNGs, etc., like label text, which you also cannot interact with. If you are looking for a button, you can pass a UIImage to Button. If you are looking to query the image, examine, alter, etc. the only option we have at the moment is to use the image as a background image for a 3D view and use the SceneWidget callbacks.

**Comment by Harry-Zhi** [comment]
> Using pyimgui is unlikely to work with Open3D's version. Pyimgui presumably includes a small library containing the ImGUI code, as does Open3D. ImGUI keeps a lot of hidden state (indexed on the object name), so you have two different copies of the library keeping two different sets of state.
> 
> The current visualization model uses raw OpenGL calls, which is simple but limited. We are in the process of replacing it, but you've come in while we're still mid-transition. However, we've recently added a new visualization module using the new UI and which combines most, if not all, of the aspects of the old visualizers (the functionality of the old visualizers was not composable, so some features were not available together with other features). This new visualization module can act as a draw_geometries() replacement, just change use `draw(...)` instead of draw_geometries. You can see the [examples/python/gui/draw.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py) example for samples of various features. Also, you can use the open3d.visualization.O3DVisualizer class directly if you wish as well (see [python/open3d/visualization/draw.py](https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py), which implements `draw()`, for sample usage). A similar C++ example is in the C++ examples. This new visualizer will be available in 0.13, or you can compile from source and try it now.
> 
> We added support for a background image in SceneWidget (technically, Open3DScene::SetBackground()) and it will be in 0.13, but we are still working on video support. You can call Open3DScene::SetBackground repeatedly, however, it will create a new texture in the Filament backend every time, and Filament can only create a fixed number of graphics items before it runs out of IDs internally and crashes. We are still working on using Filament's ability to replace the texture contents instead of creating an entirely new texture, but it is unlikely to make it in to 0.12.
> 
> What are looking to do with the ImageLabel? It was intended for use for icons, logos, displaying PNGs, etc., like label text, which you also cannot interact with. If you are looking for a button, you can pass a UIImage to Button. If you are looking to query the image, examine, alter, etc. the only option we have at the moment is to use the image as a background image for a 3D view and use the SceneWidget callbacks.

Thank you so much @prewettg for the detailed reply. Looking forward to more and more insteresting components in Open3D GUI module.
