### ISSUE TITLE
Update geometry using new rendering API

### ISSUE THREAD

**Issue by guanming001** [intel-isl/Open3D#2869]
Hi, using the previous Open3D visualizer, I am able to update geometry of a mesh using `open3d.visualization.Visualizer.update_geometry()` in a continuous loop.

However, can I ask if it is possible to perform the same action using the new rendering API (Open3D 0.12.0)?

Below are two sample codes: the first one uses the previous Open3D visualizer and the other uses the new rendering API where I am stuck on the part of updating geometry.

Sample code using previous Open3D visualizer:
```python

import time
import numpy as np
import open3d as o3d

def main():
    frame = o3d.geometry.TriangleMesh.create_coordinate_frame(1.5)
    mesh = o3d.geometry.TriangleMesh.create_sphere()
    mesh.compute_vertex_normals()

    vis = o3d.visualization.Visualizer()
    vis.create_window(width=640, height=480)
    vis.add_geometry(frame)
    vis.add_geometry(mesh)

    ctr = vis.get_view_control()
    ctr.set_lookat([0,0,0])
    ctr.set_front([1,1,1])
    ctr.set_up([0,0,1])
    ctr.set_zoom(0.5)

    i = np.tile(np.arange(len(mesh.vertices)),(3,1)).T # (8,3)
    while True:
        # Deform mesh vertices
        vert = mesh.vertices + np.sin(i)*0.02
        mesh.vertices = o3d.utility.Vector3dVector(vert)
        i += 1

        vis.update_geometry(mesh)
        vis.update_renderer()
        vis.poll_events()

        time.sleep(0.05)
        if i[0,0]>100:
            break

    vis.run()

if __name__ == "__main__":
    main()
```

Output:
![img_](https://user-images.githubusercontent.com/38412160/103800267-25ce0d80-5087-11eb-9d50-b4ac57aa4e4e.gif)

Sample code using new rendering API:
```python
import time
import threading
import numpy as np
import open3d as o3d
import open3d.visualization.gui as gui
import open3d.visualization.rendering as rendering

def main():
    gui.Application.instance.initialize()

    window = gui.Application.instance.create_window('img', width=640, height=480)
    widget = gui.SceneWidget()
    widget.scene = rendering.Open3DScene(window.renderer)
    window.add_child(widget)    

    frame = o3d.geometry.TriangleMesh.create_coordinate_frame(1.5)
    mesh = o3d.geometry.TriangleMesh.create_sphere()
    mesh.compute_vertex_normals()

    mat = rendering.Material()
    mat.shader = 'defaultLit'

    widget.scene.camera.look_at([0,0,0], [1,1,1], [0,0,1])
    widget.scene.add_geometry('frame', frame, mat)
    widget.scene.add_geometry('mesh', mesh, mat)

    def thread_main():
        i = np.tile(np.arange(len(mesh.vertices)),(3,1)).T # (8,3)
        while True:
            # Deform mesh vertices
            vert = mesh.vertices + np.sin(i)*0.02
            mesh.vertices = o3d.utility.Vector3dVector(vert)
            i += 1

            # TODO: Update geometry

            time.sleep(0.05)
            if i[0,0]>100:
                break

    threading.Thread(target=thread_main).start()

    gui.Application.instance.run()

if __name__ == "__main__":
    main()
```

**Comment by JotaCe7** [comment]
I'm trying to do same for updating position of a point cloud using gui.Button and geometry.translate[array] as a function callback.
For now calling .scene.remove_geometry and then scene.add_geometry again . Does the trick. Problem is point cloud have several hundreds of millions of points and it takes too long to update the gui. 
A scene.update_geometry function is needed.

**Comment by prewettg** [comment]
The [examples/python/gui/add-geometry.py](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/add-geometry.py) example shows how to safely alter the scene using a timer. The example adds geometry, but it could remove or add-remove as well. The important point ensuring that the scene is only updated on the main thread.

@JotaCe7's problem is different, namely that adding a geometry is very slow. There is actually an `update_geometry()` call, but it is in `open3d.visualization.rendering.Scene`, not `open3d.visualization.rendering.Open3DScene`. You can get the `Scene` from `Open3DScene` with `o3dscene.scene` (so the call is likely `widget.scene.scene.update_geometry(...)`). It does not recreate the entire object, so it can be faster. However, all new data will still need to be copied to the graphics card, so hundreds of millions of points will still take a while to update. You can speed this up somewhat by using t.geometry.PointCloud, which uses float, instead of double, and therefore does not require a conversion from double -> float to go to the video card. Also, converting normals to the format that Filament requires is also time consuming, so if normals do not need to be updated that will also help speed things up. `Scene.update_geometry()` takes flags indicating what arrays should be updated. We do not have an example for this, although there is a usage in [Open3D-ML's visualization.py](https://github.com/intel-isl/Open3D-ML/blob/3d13bfe4925204ee9a63bed3fad2f1f925e1ca8b/ml3d/vis/visualizer.py#L1108) at line 1108. See also the python bindings at [cpp/pybind/visualization/rendering/rendering.cpp:332](https://github.com/intel-isl/Open3D/blob/4927419cda0afb8d125f8af322b249ced715139f/cpp/pybind/visualization/rendering/rendering.cpp#L332)

**Comment by JotaCe7** [comment]
Hi @prewettg. Thank you for your reply.
I'm using vis-gui.py as starting pint. When I try to run:
 self._scene.scene.scene..update_geometry(geometry_name, geometry,o3d.visualization.rendering.Scene.UPDATE_POINTS_FLAG )
where
self._scene = gui.SceneWidget()
and
self._scene.scene = rendering.Open3DScene(w.renderer)
All I get is the application closes with a message: Process finished with exit code -1073740791 (0xC0000409)

Do I have to initialize the scene differently?

**Comment by JotaCe7** [comment]
@prewettg 
I see in docs that in order to use widget.scene.scene.update_geometry(...) I need to have a 'PointCloud with tensor attributes from file' read with o3d.t.io class. When I'm trying to add my pointcloud file all I get is empty scree. What is the difference between 'PointCloud with tensor attributes from file' and a simple 'PointCLoud'?

**Comment by guanming001** [comment]
Thanks @JotaCe7 and @prewettg for the suggestions, I have updated the sample code to include a simple `update_geometry()` callable that uses `clear_geometry` and `add_geometry` and the scene is updated in the main thread using `post_to_main_thread`

```python
import time
import threading
import numpy as np
import open3d as o3d
import open3d.visualization.gui as gui
import open3d.visualization.rendering as rendering

def main():
    gui.Application.instance.initialize()

    window = gui.Application.instance.create_window('img', width=640, height=480)
    widget = gui.SceneWidget()
    widget.scene = rendering.Open3DScene(window.renderer)
    window.add_child(widget)    

    frame = o3d.geometry.TriangleMesh.create_coordinate_frame(1.5)
    mesh = o3d.geometry.TriangleMesh.create_sphere()
    mesh.compute_vertex_normals()

    mat = rendering.Material()
    mat.shader = 'defaultLit'

    widget.scene.camera.look_at([0,0,0], [1,1,1], [0,0,1])
    widget.scene.add_geometry('frame', frame, mat)
    widget.scene.add_geometry('mesh', mesh, mat)

    def update_geometry():
        widget.scene.clear_geometry()
        widget.scene.add_geometry('frame', frame, mat)
        widget.scene.add_geometry('mesh', mesh, mat)   

    def thread_main():
        i = np.tile(np.arange(len(mesh.vertices)),(3,1)).T # (8,3)
        while True:
            # Deform mesh vertices
            vert = mesh.vertices + np.sin(i)*0.02
            mesh.vertices = o3d.utility.Vector3dVector(vert)
            i += 1

            # Update geometry
            gui.Application.instance.post_to_main_thread(window, update_geometry)            

            time.sleep(0.05)
            if i[0,0]>100:
                break

    threading.Thread(target=thread_main).start()

    gui.Application.instance.run()

if __name__ == "__main__":
    main()
```

![img__](https://user-images.githubusercontent.com/38412160/104866363-5f512380-5979-11eb-960e-057ca1a6cdfe.gif)

**Comment by prewettg** [comment]
@JotaCe7

**Comment by jinfagang** [comment]
AttributeError: module 'open3d.visualization.rendering' has no attribute 'Material'

**Comment by Devoe-97** [comment]
Could anyone kindly explain to me how I can save the sequence of point clouds as a visualized video?

**Comment by diplodocuslongus** [comment]
@lucasjinreal use:
`mat = rendering.MaterialRecord()`

**Comment by jtcook2** [comment]
I don't think should be closed.  In the low level scene class, add_geometry can take the base class open3d.cpu.pybind.t.geometry.Geometry of open3d.cpu.pybind.t.geometry.PointCloud. See the following link for the doctoring https://www.open3d.org/docs/release/python_api/open3d.visualization.rendering.Scene.html

This would prevent needing to remove and redraw meshes which is extremely slow. 

As a workaround I'm just sampling the mesh I'm trying to visualize, but this is much less clean than just observing the mesh.
