### ISSUE TITLE
Warning message from randering::Material?

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2881]
Hello,

When I tried the visualization::visualizer::O3DVisualizer, like the following
`
utility::SetVerbosityLevel(utility::VerbosityLevel::Debug);
visualization::rendering::Material mat;
o3dvisualizer.AddGeometry("pcd",  pcd, &mat);
`
I got the warning message
[entity=50, primitive @ 0] missing required attributes (000000000000000D), declared=0000000000000005

It seems to be some bug in rendering module. Good to debug it.

Thank you!

**Comment by 1939938853** [comment]
Need to set material.point_size value

**Comment by prewettg** [comment]
I don't think the warning is related to the verbosity level, since the Filament library prints this out. However, prior to #3184, rendering::Material did not set a value for `shader`, which is invalid. The message comes from the shader requiring an attribute that is not present. My hypothesis is that internally we defaulted to using the "defaultLit" shader, which assumes a normal, and the point cloud did not have normals. If this theory is correct, setting `mat.shader = "defaultUnlit";` should cause the warning to go away. #3184 sets `shader` to "defaultUnlit" in the constructor now, which may resolve the issue.
