### ISSUE TITLE
O3DVisualizer features request

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#2884]
Hello,

Played a little Q3DVisualizer, feel good, but need more features.

1. Clear all geometries. I can run the ClearGeometries in the SceneWidget level, but the names are still left.
2. Scene settings. Is it possible to expose out them to user?  because many application needs to program set the lighting and scene etc. Otherwise have to use the provided GUI, manually do it.  I tried auto* raw_scene = visualizer->GetScene()->GetScene(). But got undefined raw_scene error

**Comment by 1939938853** [comment]
For the visualization of point cloud with normals, open3d::visualization::visualizer is not sensitive to normal orientation. But the filament based O3DVisualizer is sensitive to normal orientation.

Is it possible make O3DVisualizer insensitive to normal orientation?

Thanks!

**Comment by prewettg** [comment]
If you want to remove geometry, you should use O3DVisualizer::RemoveGeometry() rather than using Open3DScene or Scene to do it, so that O3DVisualizer can maintains a correct understanding of what's in the scene. If you need you can use Scene::QueryGeometry() to get a list of the items in the scene, although be careful, because there are some internal items that should not be removed (usually this start with an underscore).

Most of the settings in the UI should be changeable using O3DVisualizer functions, although it looks like lighting was not included. I would recommend using visualizer->GetScene()->SetLighting() to do it with Open3DScene rather then Scene, though, as it takes care of a lot of tedious details, and also matches the lighting profiles of O3DVisualizer.

I'm not sure what you mean by "sensitive to normal orientation", do you mean that the point cloud is unlit? You can always pass a material yourself and that will override the default material used. If you use material.shader = "defaultLit", that will get you a lit point cloud.
