### ISSUE TITLE
Is it possible to display 2D Image in O3DVisualizer?

### ISSUE THREAD

**Issue by funshine** [intel-isl/Open3D#2886]
Legacy visualizer can display 2D Images geometry::Image, 
Is it possible to display/integrate 2D Images in O3DVisualizer like a video player? 
This is useful for RGBD sensor like realsense.

Currently I can display Image using scene_->GetScene()->SetBackground()

**Comment by funshine** [comment]
Currently I can display Image using scene_->GetScene()->SetBackground()

**Comment by funshine** [comment]
scene_->GetScene()->SetBackground() causes memory leak.
quick fix like this:
scene_->GetScene()->GetScene()->RemoveGeometry("__background"); // before setbackground
which is not good enough

**Comment by prewettg** [comment]
#3002 fixes the memory leak and will update the contents of the texture instead of creating a new texture (assuming the size is the same) when setting the background image. Since Filament only has a limited number of entity IDs, which it never reuses, this prevents Filament crashing when we run out of IDs for a video lasting a few minutes. This PR also introduces a VideoWidget if you don't want the video in your 3D view.

**Comment by prewettg** [comment]
#3002 will also add a new `examples/python/gui/video.py` example that illustrates how to do update the Scene's image.
