### ISSUE TITLE
ICP point to point registration fails

### ISSUE THREAD

**Issue by aycameric** [intel-isl/Open3D#3094]
Hello,

why do I get two different results with the same data when I haven't changed anything? The yellow pointcloud is a 3d model, the blue one is from an Asus RGBD Camera.

The result of global registration looks similar to the mismatched result for both outcomes.

In the well matched case:
fitness = 2.181373e-01, inlier_mse=5.685259e-03, correspondence_set size = 356 (most of the time the correspondence set size is smaller than the mismatched case, however this time it wasn't)

![ss2](https://user-images.githubusercontent.com/44435304/109194838-1c654580-779a-11eb-9a8d-5d8e5c0a8a40.png)

In the mismatched case:
fitness = 2.046569e-01, inlier_mse=5.551685e-03, correspondence_set size = 334

![ss1](https://user-images.githubusercontent.com/44435304/109194860-2129f980-779a-11eb-8ea2-7e7ce481fcc4.png)

Thank you!

**Comment by reyanshsolis** [comment]
Hi @aycameric, Sorry for the delay. 
May you please send the output transformation matrix in both the case, as well as the initial transformation matrix guess that you are using? Also, can you share your code and point cloud files [you may upload in a drive and share the link]?

Also, let us know what OS you are working on, and which Open3D version you are using. 

I will try my best to resolve your issue, Thanks for your patience. 
Regards,
Rishabh

**Comment by aycameric** [comment]
Hi @reyanshsolis,

here is the link with the requested files and info: https://drive.google.com/drive/folders/17rAAfOzE8g8wCKMyPSa0cHyvJDjUUb-R?usp=sharing

Thank you very much! 
The match looks different now, btw. but I still can't get the same registration result consistently.

Best regards,
Ayca

**Comment by satej1210** [comment]
Hello,

It seems that your voxel size was too high. By tweaking it down `voxel_size = 0.005`, I'm able to get `fitness = 76%` and `MSE = 2.443736146319934e-31`. The correspondence set size is `1241`.

The problem might be that there are not enough points to match the source to the target when `voxel_size = 0.5`. Which is why the registration can find multiple solutions (as shown in your example). Increasing the resolution of your point cloud increases the number of points in the point cloud, meaning that the fitness score will be more accurate and higher if the actual solution is found.

You can further tweak the voxel size to balance your processing time and accuracy, depending on what you need.

![s](https://user-images.githubusercontent.com/6539210/112704447-a3c0da00-8e68-11eb-9c18-3be0e890041e.gif)

**Comment by aycameric** [comment]
Hi @satej1210,

did you change anything else? If I change voxel size to 0.005 I still don't get an accurate match (see photo below)? But my fitness is at 100%.
And your match seems very good. Which version of Open3d are you using?

![bla](https://user-images.githubusercontent.com/44435304/112859477-2d63e800-90b3-11eb-98a5-6b343b4023bb.png)
