### ISSUE TITLE
O3DVisualizerWithEditing

### ISSUE THREAD

**Issue by 1939938853** [intel-isl/Open3D#3125]
Hello,

For O3DViisualizer, is it possible in the coming version to add functionalities such as mouse pick-point, mouse draw rectangle(polygon to crop geometry? Just as what was implemented in open3d::visualization::visualizer::VisualizerWithEditing.  

Thank you!

**Comment by prewettg** [comment]
Point picking is already implemented, click the "Selection" tab under "Mouse Controls". Use Ctrl + Left Click (Cmd + Left click on macOS) to select a point. Add Shift to unselect a point.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/2333353/110165964-ac6e4500-7dc1-11eb-9446-a8d06fd0d0bb.png">

Polygon selection is on our list of things to implement.

**Comment by jwesolo** [comment]
I, too, have need of this functionality, but trying to select points from point clouds simply doesn't work for me. Using O3D 0.12 and Python 3.7.6 on Windows 10.

I'm not sure what Set 1 or other sets are on the UI and, if they are collections of selected points, I'm not sure how to see the list of points.  Every time I ctrl-click a point, I get "[Open3D WARNING] Using a shader with lighting but geometry has no normals." even if I set the shader to unlit first. The background turns from black to white. Once I ctrl-click on a point, I lose the ability to navigate. Sometimes, odd shapes appear, possibly a repeating, dense pattern of points. Sometimes, Python crashes without giving an error.

There is no way to set up view control or other options for the new visualizer, from what I could tell, because there's no object to work with, just the call to draw (), which has limited options. I don't know if there's a way to change the shader ahead of time, if that's the problem.

Thanks.

**Comment by prewettg** [comment]
@jwesolo The "Set 1" (and any others that you create) are collections of selected points, along with some information like order of selection. You can pass functions to the `actions` argument of `o3d.visualization.draw()` which will give you a button and a menu item. When clicked, it will pass the `o3d.visualization.O3DVisualizer` object, from which you can query the selections. One of the examples in [`examples/python/gui/draw.py`](https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/draw.py) does this, so you can look there for details. You can also use the O3DVisualizer object directly if you wish; use the implementation of `draw()` as an example at [`python/open3d/visualization/draw.py`](https://github.com/intel-isl/Open3D/blob/master/python/open3d/visualization/draw.py)

I tried the draw.py example in Windows 10 with Python 3.8 using current `master` and did not see any problems. If `master` (or 0.13) continues to show rendering problems for you, please open a separate issue. (The warning about the shader is referencing the shader used for drawing the selection points, so you can ignore that. It is a bug which we need to fix.)

**Comment by prewettg** [comment]
@1939938853 #3252 implements polygon picking, and should be in `master` within a couple of days and 0.13 a little later. You will need to add an action to do the cropping, though, since we want to give you the flexibility to do more than just cropping with the select set.

**Comment by karlHolmquist** [comment]
Hi, didn't want to start a new issue since I'm only looking for some clarification.

0.14.1 it's possible to do polygon selection, however so far I haven't been able to extract neither the points within the polygon nor the polygon itself. Is this supported when using the draw function from python?

Separately, I haven't found a conclusive list of possible keyboard bindings for actions nor a helper function that lists all possible keyboard commands using draw (using the old visualizer the h button would print the possible keyboard bindings but that doesn't seem to be the case for the new o3dvisualizer).

Thanks beforehand
