### ISSUE TITLE
AttributeError: module 'open3d.visualization.gui' has no attribute 'ToggleSwitch'

### ISSUE THREAD

**Issue by Benjamin-Siebold** [intel-isl/Open3D#3264]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
running the https://github.com/intel-isl/Open3D/blob/master/examples/python/gui/all-widgets.py file gives errors for modules that don't exist:

AttributeError: module 'open3d.visualization.gui' has no attribute 'ToggleSwitch'

AttributeError: module 'open3d.visualization.gui' has no attribute 'ImageWidget'

**To Reproduce**

upgrade o3d

run all_widgets.py

**Expected behavior**

the modules to be installed

**Environment (please complete the following information):**

- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
- Python version: Python 3.7.7
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**

**Comment by prewettg** [comment]
The problem is that you are running the `master` branch examples with the 0.12.0 code. We've added features to the `master` branch which the 0.12 code obviously does not know about. You will need to use the 0.12 version of the examples. Unfortunately, there is not currently an easily discoverable link for this. One option is to download the source in the tags/release section of Github. Another option is to look at the code using Github's code browser, and using the tag as the branch name:  [https://github.com/intel-isl/Open3D/tree/*v0.12.0*/examples/python](https://github.com/intel-isl/Open3D/tree/v0.12.0/examples/python)

We apologize for the confusion and are trying to think of a way to conveniently link to the examples.

**Comment by Benjamin-Siebold** [comment]
ahh that makes sense. Thank you for the response!
