### ISSUE TITLE
Very large shared object when building the conda package on Ubuntu

### ISSUE THREAD

**Issue by runette** [intel-isl/Open3D#3274]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
I am building my own set of Conda packages for use with my app since I need a bug fix PR that is in the latest master but is not yet released (is it time for a new release yet?)

I am doing this using exactly the instructions as per [the docs](http://www.open3d.org/docs/release/compilation.html).

This works on all three platforms (i.e. win, macos, linux)

However - on Win and Mac I get about an 80Mib pybind.cpython shared object / dll. On Ubuntu - the so is 1Gib! and tars down to 255Mib.

This is not easily distributable!

**To Reproduce**
on Ubuntu 
util/install_deps_ubuntu.sh
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=. ..
make -j$(nproc)
make conda-package

**Expected behavior**
the so to be roughly the same size on all platforms

- Operating system: Ununtu 20.04
- Python version: Python 3.8
- Open3D version: latest Master branchj
- Is this remote workstation?:  no
- How did you install Open3D?: git clone
- Compiler version (if built from source): gcc 9.3

**Additional context**

**Comment by ssheorey** [comment]
Hi @runette , we are deprecating conda packages. Please install developer wheels in your conda environement from here. These are built from master on every new commit.
http://www.open3d.org/docs/release/getting_started.html#development-version-pip

**Comment by runette** [comment]
@ssheorey ok - thanks

It seems a shame that you deprecating conda - it does make managing multiple environments and project dependencies so much easier!

**Comment by ssheorey** [comment]
Hi @runette note that we are deprecating conda packages only. Users can continue using Open3D in a `conda` environment as before. The only change from a user's perspective is that they install Open3D with `pip` instead of `conda` in their conda environment. A safe option here is to use `conda` for creating environments and `pip` to install and manage dependencies inside the environment. See here for more information:
https://www.anaconda.com/blog/using-pip-in-a-conda-environment
