### ISSUE TITLE
Symbols from GLFW package copied into Open3D are exported to the whole application (on MacOS at least)

### ISSUE THREAD

**Issue by jackjansen** [intel-isl/Open3D#3283]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
On MacOS (at least) the open3d Python installer contains a copy of glfw in the `pybind` dll.
If you use open3d together with another package that uses a "normally installed" version of glfw things can go bad. 
 
You get error messages like the following:

```
objc[57269]: Class GLFWApplicationDelegate is implemented in both /usr/local/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-darwin.so (0x12733e7d0) and /usr/local/opt/glfw/lib/libglfw.3.dylib (0x15d660b28). One of the two will be used. Which one is undefined.
objc[57269]: Class GLFWWindowDelegate is implemented in both /usr/local/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-darwin.so (0x12733e758) and /usr/local/opt/glfw/lib/libglfw.3.dylib (0x15d660b50). One of the two will be used. Which one is undefined.
objc[57269]: Class GLFWContentView is implemented in both /usr/local/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-darwin.so (0x12733e7f8) and /usr/local/opt/glfw/lib/libglfw.3.dylib (0x15d660ba0). One of the two will be used. Which one is undefined.
objc[57269]: Class GLFWWindow is implemented in both /usr/local/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-darwin.so (0x12733e870) and /usr/local/opt/glfw/lib/libglfw.3.dylib (0x15d660c18). One of the two will be used. Which one is undefined.
```

If either open3d or the other package happens to use one glfw symbol from one library and another symbol from the other library a crash will result.

**To Reproduce**

Reproducing is difficult, because it requires creating a C extension that uses glfw.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- OSX 10.16
- Python version: 3.8
- Open3D version: current
- Is this remote workstation?:  no
- How did you install Open3D?: pip
- Compiler version (if built from source): not applicable

**Additional context**

**Comment by errissa** [comment]
@prewettg Can you take a look at this? This is a Mac issue.

**Comment by prewettg** [comment]
The following script reproduces this:
```
import glfw
import open3d as o3d
torus = o3d.geometry.TriangleMesh.create_torus()
torus.compute_vertex_normals()
o3d.visualization.draw([torus])
```
I don't know of a way that we could fix this. Both Python packages would need to link to the same library. You could build Open3D to use shared libraries and to link to the system GLFW, although since macOS does not have a system GLFW such a build would be limited to the build machine (and machines that have GLFW installed in the same path). But that would not even work for the script above, since the `glfw` package includes its own shared library.

The only way I can think of making this work is to compile Open3D to use shared libraries (`cmake .. -DBUILD_SHARED_LIBS=ON`, use `make pip-package` to create the wheel) and delete one of the copies of the libraries installed in python and create a symlink to the other version in its place. (Or maybe delete them both and symlink to a common version in /usr/local/lib or something.) This obviously is not something we can do with the wheel we provide to PyPI.
