### ISSUE TITLE
Bug in open3d::geometry::PointCloud::CreateFromRGBDImage

### ISSUE THREAD

**Issue by SouChtioui** [intel-isl/Open3D#3290]
I have the following code to retrieve  an open3d::geometry::PointCloud from a bag file recorded with intel realsense d435i camera:

```
    open3d::t::io::RSBagReader bag_reader;
    bag_reader.Open(bag_filename);
    auto im_rgbd = bag_reader.NextFrame().ToLegacyRGBDImage();
    auto frame = open3d::geometry::PointCloud::CreateFromRGBDImage(im_rgbd, bag_reader.GetMetadata().intrinsics_);
    bag_reader.Close();

```
it crashes when executing CreateFromRGBDImage, but when I replace it with CreateFromDepthImage like the following, it works fine:
```
    auto frame = open3d::geometry::PointCloud::CreateFromDepthImage(im_rgbd.depth_, bag_reader.GetMetadata().intrinsics_);
```
I used different bag files but nothing changed.

**Comment by ssheorey** [comment]
Thanks for reporting this. Please provide any output (e.g. stack trace) from the crash. Also complete all fields in the bug reporting template so that we know if this has already been reported / resolved.

Note that the legacy `CreateFromRGBDImage` requires float depth images, while depth images from IO are usually uint16_t, so you'll need to do data type conversion.

**Comment by SouChtioui** [comment]
Indeed @ssheorey, converting the depth to float image solved the problem.
```
    auto rgbd_image = open3d::geometry::RGBDImage::CreateFromColorAndDepth(im_rgbd.color_, *im_rgbd.depth_.CreateFloatImage());
    auto frame = open3d::geometry::PointCloud::CreateFromRGBDImage(*rgbd_image, bag_reader.GetMetadata().intrinsics_);
```
