### ISSUE TITLE
Open3D and PyQt5 fail to run together in linux

### ISSUE THREAD

**Issue by Mossi8** [intel-isl/Open3D#3367]
Hi, ``
I have tried to make my own GUI with open3D and PyQt5 and was working great in MacOS. However, when I try to run it on linux ubuntu 20.0 they seem to clash and PyQt5 window does not show until open3d visualization window is closed.  Everything is run on python 3.8, and open3d 0.12 and Pyqt5.14.2.

Any ideas why this is happening? I know you have you own GUI but I wanted to add other kind of features.

Example code:

from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QLabel, QVBoxLayout, QWidget

import sys
import open3d as [`o3d`](url)
from random import randint
import numpy as np

class MainWindow(QWidget):
    
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout()
        self.label = QLabel("Another Window % d" % randint(0,100))

        layout.addWidget(self.label)
        self.setLayout(layout)
        self.show()
        
vis = o3d.visualization.Visualizer()
vis.create_window(height=2000,width=2000,top=0,left=500)
x= np.random.random_integers(0,1000,10000)
y = np.random.random_integers(0,1000,10000)
z = np.zeros_like(x)

p = np.stack([x,y,z]).T
c = np.ones([x.shape[0],3])*0.5#np.concatenate(colors)[:,0,:]

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(p)
pcd.colors = o3d.utility.Vector3dVector(c)   

vis.add_geometry(pcd)
opt = vis.get_render_option()

opt.background_color = np.asarray([0, 0, 0])

app = QApplication(sys.argv)
w = MainWindow()

vis.run()
vis.destroy_window()

app.exec_()

Thanks in advance

**Comment by prewettg** [comment]
I'm surprised that you don't see the same behavior in macOS, actually. But your problem is that `vis.run()` is blocking, so `app.exec_()` isn't going to be executed until the vis window has finished. You'd need to call `vis.poll_events()` and `vis.update_renderer()` in a loop, but you'd also have to do the equivalent with Qt. It looks like you could call the Python equivalent of `QCoreApplication::processEvents()` in the loop. However, mixing two UI systems is unpleasant at best and untenable at worst. If you want to use Qt for UI, I would recommend that you also use Qt for rendering. And vice-versa. Open3D has a new GUI system which has most of the widgets you'd find in Qt, which you can find in open3d.visualization.gui, along with some examples in `examples/python/gui`.
