### ISSUE TITLE
Visualizer changes directories on MacOS by itself

### ISSUE THREAD

**Issue by aurelien-m** [intel-isl/Open3D#3471]
**Describe the bug**
When calling `create_window()` from a `visualization.Visualizer()` object, it changes the current Python directory to `/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/Resources` on MacOS.

**To Reproduce**

```Python
import open3d as o3d
import os

vis = o3d.visualization.Visualizer()
print(os.getcwd()) # path/where/Python/is/executed
vis.create_window()
print(os.getcwd()) # /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/Resources
```

**Expected behavior**
Is it normal that it's changing my current directory? My co-worker has told that it has no directory changing effect on Ubuntu.

**Environment:**

- Operating system: OSX 10.15.7
- Python version: Python 3.8.2
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by prewettg** [comment]
We use GLFW to handle windows, and [`glfwInit()`](https://www.glfw.org/docs/3.3/group__init.html#ga317aac130a235ab08c6db0834907d85e) sets the current directory to the resource directory. Since you are appear to be using a version of Python with framework bundle, the resource directory of that bundle is used. If you use a Python that is not a framework bundle, such as from MacPorts (and presumably Brew, although I have not tried it), the directory will not be changed, since there is no resource directory.
