### ISSUE TITLE
[Question] How to edit the tutorial.json and conduct run_system.py of reconstruction_system

### ISSUE THREAD

**Issue by Yusei19990405** [intel-isl/Open3D#3514]
Hello, I started using reconstruction system in Open3D.
Also, I'm trying to run the examples/python/reconstruction_system/run_system.py with the config/tutorial.json like the command below.

$ python3 run_system.py config/tutorial.json --make

In addition, I downloaded the image and depth folder from 
https://drive.google.com/open?id=11U8jEDYKvB5lXsK3L1rQcGTjp0YmRrzT to conduct reconstruction system in the dataset folder.

Now, I'm editing "path_dataset" in the tutorial.json but it does not work well. 

So, I want to know how to edit the tutorial.json and carry out the run_system.py.

I refer to http://www.open3d.org/docs/release/tutorial/reconstruction_system/system_overview.html

**Comment by ssheorey** [comment]
@Yusei19990405 are you asking for documentation about the parameters in `tutorial.json`?

**Comment by Yusei19990405** [comment]
Yes. However, I solved this problem on Tuesday. 
So, no information about "tutorial.json" is necessary.

Thank ssheorey.

I close this issue.

**Comment by hyung-ju-song** [comment]
Hi thanks in advance
I am running the same tutorial as you.

But there are **two** problems.

The first is when using the **SceneNN dataset** provided by open3d.
With **python run_system.py tutorial.json --make** , I succeeded in creating 13 fragments, but **--register** does not work. So I haven't tried it since then.

The error is:
------------------------------------------------------------ ------------------------------------------------------------ ------------
TypeError: registration_colored_icp(): incompatible function arguments. The following argument types are supported:
    1. (source: open3d.cpu.pybind.geometry.PointCloud, target: open3d.cpu.pybind.geometry.PointCloud, max_correspondence_distance: float, init: numpy.ndarray[float64[4, 4]] = array([[1] .,
0., 0., 0.], ...

------------------------------------------------------------ ------------------------------------------------------------ ------------
 
The second is a problem when using **my custom dataset**.
json file by duplicating something like the above
It works in the same way, but the **ply file** is not created in the fragments folder. Only **json files** are created.
If anyone has experienced or solved this problem, please help me.

**Comment by Yusei19990405** [comment]
Hi, I tell you some information about the second problem you faced. I'm sorry I didn't experience the first problem.

When you want to get ply file by "run_system.py", you need to carry out 4 steps which are make, register, refine and integrate.
Please refer to the following works. If it success, you will be able to find ply file in scene folder.

python run_system.py 【config file】--make
python run_system.py 【config file】--register
python run_system.py 【config file】--refine
python run_system.py 【config file】--integrate

Before you carry out these works above, you need to save "color images", "depth images" and "camera_intrinsic.json" and edit the config file you use like "tutorial.json"

If you have any questions, please tell me or other members.
