### ISSUE TITLE
How to get number of iterations for ICP convergence 

### ISSUE THREAD

**Issue by Jonapple** [intel-isl/Open3D#3559]
Hi, 

I'm using Python to run the fast global registration and ICP registration in this library, the result is nice, I could get fitness, inlier_rmse and transformation matrix for each run. But for the ICP, it just gave me the final result. Is there any way to get how many time of iterations used for the ICP convergence to get the final result?

Much appreciate

**Comment by reyanshsolis** [comment]
Hi @Jonapple,
May you please refer to the issue #2901 and #3571, and see if the same resolve your issue.
To get these values you may tweak the `RegistrationICP` function in C++ to dump these values. Since the python function is just a pybind, the values will be dumped by the c++ function when is called through the python pybind. 

Closing this issue, for now, feel free to reopen, if this comment does not resolve your issue.

**Comment by heethesh** [comment]
+1 for the feature request to return the number of iterations in the registration result

**Comment by reyanshsolis** [comment]
Added option to save loss_log in a TesnsorMap in PR #4271.

Thanks!

**Comment by heethesh** [comment]
@reyanshsolis will this support also be added to the legacy registration pipeline?
