### ISSUE TITLE
X-Ray rendering

### ISSUE THREAD

**Issue by ezorfa** [intel-isl/Open3D#3672]
Hi @benjaminum @prewettg @syncle @yxlao 

Would it be possible to do an X-Ray rendering with Open3d? If not, could you suggest how can I integrate such a feature (possibly from some external libraries)?

Thanks a lot!

**Comment by ssheorey** [comment]
Hi @ezorfa can you describe your use case / application in more detail? Some example renderings / images would be useful to understand what you are trying to do.

**Comment by ezorfa** [comment]
My use case is in the medical imaging. For example, If there is a hand 3d model, then an X-Ray image would look like the following:

<img width="217" alt="Screenshot 2021-07-02 at 03 45 10" src="https://user-images.githubusercontent.com/50787308/124208469-e89f8100-dae7-11eb-863e-01b0e3791c2a.png">

**Comment by masterchop** [comment]
You might want to check with them [link](https://www.youtube.com/watch?v=xUjx88M9YFw)

**Comment by ezorfa** [comment]
Thanks @masterchop but thats not what I am interested in. Since I can visualize a mesh in Open3D, it would be nice that I can render an X-ray as well for my use case.

**Comment by masterchop** [comment]
Not sure I follow an x-ray is an image, Open3D don't do meshes from images as far as I know.

**Comment by ezorfa** [comment]
@masterchop Basically, I am interested in creating an X-ray image from the a 3d model visualized in Open3D.

**Comment by ezorfa** [comment]
Hi @benjaminum @prewettg @syncle @yxlao @masterchop @ssheorey !

I think the technical term for my usecase is the volumetric rendering. So, would it be possible with Open3D?

**Comment by ssheorey** [comment]
I don't believe this is a good fit for Open3D. Rendering X-rays requires working with a full 3D model of the object (including interior structure) while Open3D (including rendering) exclusively works with object surfaces only, since that is all  you need for visual applications such as AR/VR, robotics and visualization.

A dedicated X-Ray simulator would be more appropriate here. Perhaps something like this?
https://gmrv.es/gmrvvis/xraysim/
