### ISSUE TITLE
configurable zoom max and min

### ISSUE THREAD

**Issue by hironoriyh** [intel-isl/Open3D#497]
Currently the visualizer has the max and min zoom. This results in objects vanishing in the view when the object pose is set outside of the max-min zoom range.

Would it be possible to make the zoom range configurable?

**Comment by JeremyBYU** [comment]
I am running into the same issue.  It seems to be related to this: https://github.com/intel-isl/Open3D/issues/803 

The basic idea is that the object in the environments (large) are not being drawn because the far clipping plane is too near: https://github.com/intel-isl/Open3D/blob/fab6441b763b4964ef898cbb3fae8d10ef98442f/src/Visualization/Visualizer/ViewControl.cpp#L69

A simple change to allow this to work would be able to have a parameter to increase the max zoom, which is hard coded to 2.0.  https://github.com/intel-isl/Open3D/blob/fab6441b763b4964ef898cbb3fae8d10ef98442f/src/Visualization/Visualizer/ViewControl.cpp#L43

In my case I have point clouds that are translating dynamically through the environment. I need to be able to zoom out for them to be drawn in the window, but I can not because I am limited to how much I can zoom out.

**Comment by JeremyBYU** [comment]
A not so great workaround that I have implemented. Basically you press the key 'C' to recenter the bounding box of the point cloud.

```python
def center_view(vis):
    vis.reset_view_point(True)


vis = o3d.visualization.VisualizerWithKeyCallback()
vis.create_window()
vis.register_key_callback(ord("C"), center_view)
# Your Code
# Loop
while True:
    # Update your geometries, possibly large translations
    vis.update_geometry()
    vis.poll_events()
    vis.update_renderer()
    time.sleep(1/60)

```

**Comment by germanros1987** [comment]
This is done in the new visualizer.

**Comment by iAmJuan550** [comment]
any solution to this? I have pointcloud from a small room and I want to be able to visualize it by zooming in

**Comment by javiertg9** [comment]
When using [`Visualizer`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.Visualizer.html) and its extensions ([`VisualizerWithEditing`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.VisualizerWithEditing.html), [`VisualizerWithKeyCallback`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.VisualizerWithKeyCallback.html), [`VisualizerWithVertexSelection`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.VisualizerWithVertexSelection.html)), I think there is somewhat dirty solution to the issue that @hironoriyh mentioned.

To add some context, the workaround proposed @JeremyBYU has the advantage that, by calling `vis.reset_view_point(True)`, the bounding box of what needs to be rendered is also reset:
https://github.com/isl-org/Open3D/blob/47e2c7d1e3c19ed8936714d8066f288f83f22bf3/cpp/open3d/visualization/visualizer/Visualizer.h#L231-L232

This also allows to avoid the depth-range clipping mentioned in #803 without the need of moving to the `O3DVisualizer` (I am finding it more difficult to work with in a non-blocking way). 

However, by only calling `vis.reset_view_point(True)`, interaction with the viewer is barely allowed (see example below) because of the corresponding reset.

This is resolved by saving the viewpoint before the reset and loading it afterwards:
```python
cam = vis.get_view_control().convert_to_pinhole_camera_parameters()
vis.reset_view_point(True)
vis.get_view_control().convert_from_pinhole_camera_parameters(cam)
```

As suggested by @qianyizh, below I post a (toy) example for each case.

<details>
<summary>[code to reproduce (Open3D version: 0.16)]</summary>

```python
import open3d as o3d
import numpy as np
import time

if __name__ == "__main__":
    vis = o3d.visualization.Visualizer()
    vis.create_window(height=480, width=640)

    sphere1 = o3d.geometry.TriangleMesh.create_sphere(0.5)
    sphere1.paint_uniform_color((0.8, 0.0, 0.0))
    vis.add_geometry(sphere1)

    sphere2 = o3d.geometry.TriangleMesh.create_sphere(0.5)
    sphere2.paint_uniform_color((0.8, 0.0, 0.0))
    vis.add_geometry(sphere2)

    dt = 0.2
    s = time.time()

    # run non-blocking visualization.
    keep_running = True
    while keep_running:

        if time.time() - s > dt:
            s = time.time()
            sphere2.translate(np.array([0.1, 0.0, 0.0]))
            vis.update_geometry(sphere2)

            # workaround.
            # 1) Comment the 3 lines for the original behavior.
            # 2) Only comment the 1st and 3rd lines for reset only.
            # 3) Uncomment the 3 lines for the complete workaround.
            cam = vis.get_view_control().convert_to_pinhole_camera_parameters()
            vis.reset_view_point(True)
            vis.get_view_control().convert_from_pinhole_camera_parameters(cam)

        keep_running = vis.poll_events()
        vis.update_renderer()

    vis.destroy_window()
```

</details>

|   | original behavior |  `vis.reset_view_point(True)` |  previous block-code |
|:---|:---:|:---:|:---:|
|   | ![orig][1] | ![reset][2] | ![full][3] |
| Solve depth clipping | ❌ | ✔️ |  ✔️ |
| Relax zoom restriction | ❌ | ✔️ |  ✔️ |
| Allow full interaction | ❌ | ❌ |  ✔️ |

[1]: https://user-images.githubusercontent.com/71815905/206064546-a7ff3901-4f68-4e5f-b1bc-998572b5fef6.gif
[2]: https://user-images.githubusercontent.com/71815905/206065293-79ca76a3-06b9-4af4-b16a-d8e691eb2238.gif
[3]: https://user-images.githubusercontent.com/71815905/206065737-ec279dc8-95ac-44e4-80ff-3992f2d8d880.gif

**Comment by richardrl** [comment]
> When using [`Visualizer`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.Visualizer.html) and its extensions ([`VisualizerWithEditing`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.VisualizerWithEditing.html), [`VisualizerWithKeyCallback`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.VisualizerWithKeyCallback.html), [`VisualizerWithVertexSelection`](http://www.open3d.org/docs/latest/python_api/open3d.visualization.VisualizerWithVertexSelection.html)), I think there is a somewhat dirty solution to the issue that @hironoriyh mentioned.
> 
> To add some context, the workaround proposed @JeremyBYU has the advantage that, by calling `vis.reset_view_point(True)`, the bounding box of what needs to be rendered is also reset:
> 
> https://github.com/isl-org/Open3D/blob/47e2c7d1e3c19ed8936714d8066f288f83f22bf3/cpp/open3d/visualization/visualizer/Visualizer.h#L231-L232
> 
> This also allows to avoid the depth-range clipping problem mentioned in #803 without the need of moving to the `O3DVisualizer` (I am finding it more difficult to work with, in a non-blocking way).
> 
> However, by only calling `vis.reset_view_point(True)`, interaction with the viewer is barely allowed (see example below) because of the corresponding reset.
> 
> This is resolved by saving the viewpoint before the reset and loading it afterwards:
> 
> ```python
> cam = vis.get_view_control().convert_to_pinhole_camera_parameters()
> vis.reset_view_point(True)
> vis.get_view_control().convert_from_pinhole_camera_parameters(cam)
> ```
> 
> As suggested by @qianyizh, below I post a (toy) example for each case.
> 
> [code to reproduce (Open3D version: 0.16)]
> ```python
> import open3d as o3d
> import numpy as np
> import time
> 
> if __name__ == "__main__":
>     vis = o3d.visualization.Visualizer()
>     vis.create_window(height=480, width=640)
> 
>     sphere1 = o3d.geometry.TriangleMesh.create_sphere(0.5)
>     sphere1.paint_uniform_color((0.8, 0.0, 0.0))
>     vis.add_geometry(sphere1)
> 
>     sphere2 = o3d.geometry.TriangleMesh.create_sphere(0.5)
>     sphere2.paint_uniform_color((0.8, 0.0, 0.0))
>     vis.add_geometry(sphere2)
> 
>     dt = 0.2
>     s = time.time()
> 
>     # run non-blocking visualization.
>     keep_running = True
>     while keep_running:
> 
>         if time.time() - s > dt:
>             s = time.time()
>             sphere2.translate(np.array([0.1, 0.0, 0.0]))
>             vis.update_geometry(sphere2)
> 
>             # workaround.
>             # 1) Comment the 3 lines for the original behavior.
>             # 2) Only comment the 1st and 3rd lines for reset only.
>             # 3) Uncomment the 3 lines for the complete workaround.
>             cam = vis.get_view_control().convert_to_pinhole_camera_parameters()
>             vis.reset_view_point(True)
>             vis.get_view_control().convert_from_pinhole_camera_parameters(cam)
> 
>         keep_running = vis.poll_events()
>         vis.update_renderer()
> 
>     vis.destroy_window()
> ```
> 
> original behavior	`vis.reset_view_point(True)`	previous block-code
> ![orig](https://user-images.githubusercontent.com/71815905/206064546-a7ff3901-4f68-4e5f-b1bc-998572b5fef6.gif)	![reset](https://user-images.githubusercontent.com/71815905/206065293-79ca76a3-06b9-4af4-b16a-d8e691eb2238.gif)	![full](https://user-images.githubusercontent.com/71815905/206065737-ec279dc8-95ac-44e4-80ff-3992f2d8d880.gif)
> Solve depth clipping	❌	✔️	✔️
> Relax zoom restriction	❌	✔️	✔️
> Allow full interaction	✔️	❌	✔️

Great post, but I got this error when using the last line in your code snippet:

[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.


vis.get_view_control().convert_from_pinhole_camera_parameters(cam)

**Comment by javrtg** [comment]
Hi @richardrl , I can reproduce the error you are having, and I believe it is caused by the bug mentioned in #6666.

This bug has been fixed in #6711. However, the latest pypi release of Open3D (0.18.0) still contains the bug.

The reason this error shouldn't occur is that the `convert_from_pinhole_camera_parameters` method does the following checks:
https://github.com/isl-org/Open3D/blob/525c4e6567f3a885f930571c3cc83233e35573aa/cpp/open3d/visualization/visualizer/ViewControl.cpp#L178-L189

These checks ensure that the dimensions (height and width) of the viewer match those of the camera being set. Since we are keeping the dimensions unchanged, there shouldn't be any error.

As a workaround to avoid being affected by the bug, you can set the optional argument [`allow_arbitrary`](https://www.open3d.org/docs/release/python_api/open3d.visualization.ViewControl.html#open3d.visualization.ViewControl.convert_from_pinhole_camera_parameters), to `True`, like so:
```python
# change this line:
vis.get_view_control().convert_from_pinhole_camera_parameters(cam)
# to this line:
vis.get_view_control().convert_from_pinhole_camera_parameters(cam, allow_arbitrary=True)
```

**Comment by richardrl** [comment]
@javrtg Thanks for your response. However, the allow_arbitrary code seems to do something weird to the camera. I can't really translate it with CTRL + ALT + left drag anymore.

**Comment by javrtg** [comment]
@richardrl I find that a bit strange because (at least with open3d 0.18.0) I can still translate the camera using either of:
* CTRL + ALT + left drag
* Wheel button + left drag

Maybe something else is causing the visualizer to block?
