### ISSUE TITLE
[Question] Can we export TSDFVolume into numpy array?

### ISSUE THREAD

**Issue by bing-jian** [intel-isl/Open3D#519]
I guess current implementation does not support this feature according to
https://github.com/IntelVCL/Open3D/blob/master/src/Python/Core/open3d_integration.cpp

Basically, in addition to extract_point_cloud() and extract_triangle_mesh(),  it would be nice if we can also export the actual tsdf volume into a numpy array after running integrate function.

Thanks,
Bing

**Comment by LittleLampChen** [comment]
Is this be solved?
I also need the same feature. If we can access TSDF value by np.asarray, some operation will be flexible.
In TSDF presentation, only the voxel near the surface will have different value with max threshold, the rest value is all the same. Actually, in many applying scenes, there will be large part of voxels with same value, which is far away from surface. So, can we just return an array which only contains the voxels indices and value which is near the surface. 
And, I think this will be efficient.

**Comment by Leerw** [comment]
@LittleLampChen @bing-jian @syncle Has this solved? I also want to access the TSDF volume values but I found no related source codes in this repo.

**Comment by oafolabi** [comment]
@syncle, @bing-jian .This would be a useful functionality. Maybe we could instead provide a function that allows us query the tsdf? That way you can leave the storage problem to the user.

**Comment by theNded** [comment]
Current ScalableTSDF is stored in an [unordered_map](https://github.com/intel-isl/Open3D/blob/master/src/Open3D/Integration/ScalableTSDFVolume.h#L94). The conversion may be non trivial.

One possible workaround can be returning two vectors, (n, 3) for keys and (n, resolution^3) for tsdfs. Users are responsible for reshaping these outputs. This process can also be reverted, so that we can construct a ScalableTSDFVolume from np arrays with proper shapes. @syncle do you think it is reasonable to add this functionality? I can work on this.

In our roadmap, these data structures will be replaced by tensors that can be directly accessed by numpy or pytorch.

**Comment by ishikaa25** [comment]
So is there a way to extract the voxel grid from Scalable TSDF?

**Comment by joerowelll** [comment]
I am also interested in this, has it been implemented?
