### ISSUE TITLE
Fail to reproduce results on Augmented ICL-NUIM

### ISSUE THREAD

**Issue by theNded** [intel-isl/Open3D#540]
**Describe the problem**
The provided reconstruction system fail to reproduce the [results](http://redwood-data.org/indoor/models.html) for [Augmented ICL-NUIM](http://redwood-data.org/indoor/dataset.html). 
Reconstruction with clean input depth images generates model with high quality. However, when we switch to depth with simulated noise, misaligned models are generated. I assume the [models in gallery](http://redwood-data.org/indoor/models.html) are generated from data with noise, since the surfaces are rough in appearance.

**To Reproduce**
- Intrinsic parameters are 525, 525, 319.5, 239.5. This is not described on the [page](http://redwood-data.org/indoor/dataset.html), so we choose the [convention](http://qianyi.info/scenedata.html) of redwood datasets.
- max_depth: 2.5, 3.0, 3.5, 4.0 are tested
- voxel_size: fixed to 0.05.
- max_depth_diff: 0.03, 0.05, 0.07 are tested,
- tsdf_cube_size: fixed to 3.0,
- icp_method: color,
- With and without OpenCV are both tested.

**Outputs**
For the clean depth input, the results are quite good:
![snapshot00](https://user-images.githubusercontent.com/6127282/45126831-6d54cf80-b143-11e8-8cd6-cd9b298f903a.png)

For the input depth with noise, most of the reconstructed fragments are correct, but the final models are in a mess:
- Livingroom
![snapshot00](https://user-images.githubusercontent.com/6127282/45126567-f8cd6100-b141-11e8-8fec-8b38e498f649.png)
![snapshot01](https://user-images.githubusercontent.com/6127282/45126569-f8cd6100-b141-11e8-9cff-fe9ed249ab54.png)
- Office is better, but still there are misalignments
![snapshot00](https://user-images.githubusercontent.com/6127282/45126630-52ce2680-b142-11e8-9fd6-a00542946a05.png)
![snapshot01](https://user-images.githubusercontent.com/6127282/45126631-52ce2680-b142-11e8-9672-7a7c440db57c.png)

Could you please specify the parameters and configurations to reproduce the [results](http://redwood-data.org/indoor/models.html)? Or is it possible that up to now not all the functions of the reconstruction system are implemented in Open3D?

Thank you.

**Comment by syncle** [comment]
Hi @theNded. Thanks for the through tests. Open3D is implemented from scratch, so there might be discrepancy with [redwood reconstruction system](http://redwood-data.org/indoor/pipeline.html). 

I would like to recommend the followings:
- Please try using ReconstructionSystem/visualize_fragments.py to verify all the fragments are reconstructed reasonably.
- If the fragments are good, the root-cause I suspect is the global registration. The issue may arose from incorrect parameter set for fast global registration, or there is a bug there. To check out this, I would like to suggest you can try RANSAC instead of fast global registration. For example, please replace https://github.com/IntelVCL/Open3D/blob/16cb1fec715227db9cc259bd75961146a224b6d1/examples/Python/ReconstructionSystem/register_fragments.py#L25-L35 with the following:
```
    result = registration_ransac_based_on_feature_matching(
            source_down, target_down, source_fpfh, target_fpfh,
            distance_threshold,
            TransformationEstimationPointToPoint(False), 4,
            [CorrespondenceCheckerBasedOnEdgeLength(0.9),
            CorrespondenceCheckerBasedOnDistance(distance_threshold)],
            RANSACConvergenceCriteria(4000000, 500))
```
- actually there is a code for benchmarking RANSAC and Fast global registration. Please consider try this with examples/Python/Benchmark/ and evaluate results using [this matlab script](https://github.com/qianyizh/ElasticReconstruction/tree/master/Matlab_Toolbox) to check performance of RANSAC and FGR.

**Comment by theNded** [comment]
Hi @syncle , thanks for your detailed explanation and instructions. I will give feedback ASAP.

**Comment by qianyizh** [comment]
Yes, this is a known issue and **should** be fixed by robust pose graph optimization. If you are interested you can read this page, its main purpose is to solve these erroneous registration results: http://redwood-data.org/indoor/data/choi2015cvpr.pdf

The corresponding script is:
http://www.open3d.org/docs/tutorial/ReconstructionSystem/register_fragments.html#multiway-registration
It is **supposed** to solve this issue. Can you try to play with the parameters a bit and see what the pruned edges are? This should help.

@syncle have you tested the latest script on redwood dataset? I have seen some nontrivial changes to registration part, e.g., the success criteria got removed. Can this be the reason of this issue?

**Comment by qianyizh** [comment]
@syncle I know you are on vacation, but I need you to help me on this, :)

**Comment by theNded** [comment]
@qianyizh sorry for the late reply, I was busy in the last few days.

I read the paper and play with the parameters (with upgraded Open3D).
Before pruning, there are 29 nodes and 157 edges in the pose graph.
Here is the table of remaining edges count after choosing various thresholds:

| Threshold | Number of edges |
|--|--|
|0.25 | 38 |
|0.8 | 37 |
|0.9 | 34 |
|0.95 | 31 |
|0.98 | 30 |

Even with the threshold of 0.98, the results still look the same. 

I try to read the C++ source code. 
```cpp
```

**Comment by theNded** [comment]
@qianyizh sorry for the late reply, I was busy in the last few days.
@syncle sorry to interrupt your vacation.

I read the paper and played with the parameters (with upgraded Open3D).
Before pruning, there were 29 nodes and 157 edges in the pose graph.
Here is the table of remaining edges count after choosing various thresholds:

| Threshold | Number of edges |
|--|--|
|0.25 | 38 |
|0.8 | 37 |
|0.9 | 34 |
|0.95 | 31 |
|0.98 | 30 |

Even with the threshold of 0.98, the results still look the same. 
I also tried GaussNewton instead of LM, but it converges to the same result, so the problem may be elsewhere.

I checked C++ code (misunderstood something but finally figured out hence the post was deleted) but it was hard to note the differences, since the previous version was written in g2o. 
One minor comment: in the function `ComputeLinearSystem` the comment should be `[-p_x | I]`.

BTW, I have a code base doing TSDF integration, ICP, and meshing using CUDA (https://github.com/IntelVCL/Open3D/issues/412), and I am working on refactoring it. If you are interested I will be happy to contribute to your project.

**Comment by syncle** [comment]
>  the comment should be [-p_x | I]

I just checked, but cannot see what is wrong. Can you tell specific line and reasons?

>  I have a code base doing TSDF integration, ICP, and meshing using CUDA (#412), and I am working on refactoring it. If you are interested I will be happy to contribute to your project.

That would be great! We are always welcome to your contribution.

**Comment by theNded** [comment]
https://github.com/IntelVCL/Open3D/blob/0bf814dd5022003652b7c202fcebc4c8a7136754/src/Core/Registration/GlobalOptimization.cpp#L174-L178

In [Choi 2015] Eq(7) and other documents e.g. http://ethaneade.com/lie.pdf, there should be a negative sign before the cross product operator. Please correct me if you are using other conventions.

**Comment by syncle** [comment]
I got the point. I fixed it in my working branch.

**Comment by theNded** [comment]
Mostly resolved in the new SLAC branch. To be entirely fixed upon tuning and merging.
