### ISSUE TITLE
Inheritance of classes

### ISSUE THREAD

**Issue by Toraudonn** [intel-isl/Open3D#572]
I've used Pybind11 before and I know that you can inherit classes.

I'm currently creating a custom class in python for visualization:

```
class CustomVisualization:
    def __init__(self):
        self.vis = open3d.Visualizer()
```

But I'm considering inheriting from the o3.Visualizer like this:

```
class CustomVisualization(open3d.Visualizer):
    def __init__(self):
        open3d.Visualizer.__init__(self)
```

But it comes out as:

```
TypeError: pybind11::init()" unable to convert returned instance to required alias class: no `Alias<Class>(Class &&)` constructor available
```

I looked through [open3d.h](https://github.com/IntelVCL/Open3D/blob/master/src/Python/open3d.h) and found the `bind_default_constructor`, but I don't know how to change this in order to inherit it.

**Comment by qianyizh** [comment]
I don't think the reason is ``bind_default_constructor``. It is actually just a simple wrapper of the C++ default constructor.

The real reason might be that ``Visualizer`` is a trampoline class, because the C++ class under the hood is has virtual functions. See this.
https://github.com/IntelVCL/Open3D/blob/master/src/Python/Visualization/open3d_visualization_trampoline.h
And ``Visualizer`` is bounded with ``PyVisualizer`` via:
```
    py::class_<Visualizer, PyVisualizer<>, std::shared_ptr<Visualizer>>
            visualizer(m, "Visualizer");
```

I don't have a good solution for this. But this might be the direction to look into.

**Comment by Robert-Ven** [comment]
I am not sure whether I should open a new issue or reply here, but as my issue is he same as here, I'll reply here. I attempt to create a child class for the class Pointcloud in open3d:
```
class ChildPC(open3d.geometry.PointCloud): 
    def __init__(self): 
        open3d.geometry.PointCloud.__init__(self)
```
This results in the same TypeError as in the original question.

I did find the script which binds the pointcloud, but this did not clarify much for me.
```
void pybind_pointcloud(py::module &m) {
    py::class_<PointCloud, PyGeometry3D<PointCloud>,
               std::shared_ptr<PointCloud>, Geometry3D>
            pointcloud(m, "PointCloud",
                       "PointCloud class. A point cloud consists of point "
                       "coordinates, and optionally point colors and point "
                       "normals.");
    py::detail::bind_default_constructor<PointCloud>(pointcloud);
    py::detail::bind_copy_functions<PointCloud>(pointcloud);
```


@haruishi43, were you able to solve this issue for your class?

**Comment by simleo** [comment]
I was recently affected by this. The problem is that [bind_default_constructor](https://github.com/isl-org/Open3D/blob/a167efb1852abd291b7fa8f03593d448d29737e4/src/Python/open3d.h#L56) (snapshot of the code at the time this issue was opened) uses a factory function, and that requires some extra tweaking when trampoline classes are involved, as explained [here](https://pybind11.readthedocs.io/en/stable/advanced/classes.html#custom-constructors) (see the paragraph starting with "When combining factory functions constructors with virtual function trampolines...")

**Comment by cwreynolds** [comment]
For what it is worth, I ran into this problem yesterday. I wanted to make a tiny extension to an Open3D Visualizer class and got the same message:

    TypeError: pybind11::init(): unable to convert returned instance to required alias class: no `Alias<Class>(Class &&)` constructor available
