### ISSUE TITLE
Equivalent of ReconstructionSystem in c++

### ISSUE THREAD

**Issue by EmmanuelCos** [intel-isl/Open3D#593]
Hello,
I saw that the functions implemented under the directory \ReconstructionSystem seem very appropriate to do refined 3D reconstruction. 
I am developing in C++ and need to do some 3D reconstruction, is there an equivalent existing project coded in c++?
Thank you,
Emmanuel

**Comment by syncle** [comment]
Not yet. This is lower priority because the Reconstruction system is being actively developed with Python, and it optionally uses OpenCV. Using OpenCV module in Python is straightforward and being supported, but adding OpenCV as a C++ dependency requires some discussion since we are trying to providing "easy to use" library.

**Comment by germanros1987** [comment]
@EmmanuelCos before I close this old issue I would like to say that @theNded is working on a new CUDA reconstruction system that will be around in Open3D soon.
