### ISSUE TITLE
UniformTSDFVolume with rectangular cuboid shape?

### ISSUE THREAD

**Issue by martinakos** [intel-isl/Open3D#602]
**Feature request.**
I see UniformTSDFVolume only creates cubic volumes of side length.
I would like to be able to define a rectangular cuboid TSDF volume with (width, height, depth) parameters. 
I'm trying to reconstruct objects using TSDFs and the object may be very elongated, for which at the moment I have to make a large enough cube to include the object. There is a lot of space unused in this TSDF and it makes the runtime slower than it could be if I could adjust the volume to the TSDF to my target object.

**Comment by syncle** [comment]
Hi @martinakos, how about using ``ScalableTSDFVolume`` instead? It has no bounds, and actually faster than ``UniformTSDFVolume``, so that it will be good fit for any shape. I would keep ``UniformTSDFVolume`` as is because ``ScalableTSDFVolume`` utilizes ``ScalableTSDFVolume`` as a base data structure.

**Comment by martinakos** [comment]
I think that ScalableTSDFVolume doesn't work for my needs. I understand that ScalableTSDFVolume uses a spatial hash and this is faster than a UniformTSDFVolume to integrate pointclouds for scene reconstruction. However, I'm trying to do object reconstruction and I can estimate the volume of the object before starting, so I can size a  UniformTSDFVolume as tightly as posible to the object. At the moment I can run my test at 7fps and allows me to interactively select and reconstruct the target object. I found that smaller TSDF volumes result in higher fps. 

I have tried using ScalableTSDFVolume in my object reconstruction test, and I find I can hardly get 1fps with it. I imagine the spatial hash is faster but as it's integrating every depth in the rgbd image ends up being slower for my application. The UniformTSDFVolume only integrates the depths that fall within the target volume. Furthermore, if I use ScalableTSDFVolume, after collecting a whole scene reconstruction I still have to isolate my target object from it which may not be trivial. However, with the UniformTSDFVolume I already have it isolated my target object from the beginning.

**Comment by qianyizh** [comment]
Got it. One way you can try with ScalableTSDFVolume is to pre-prune your depth image before sending in for integration. A simple way is to just remove points with large depth (e.g., any depth farther than 2m). A more complicated way is to create a point cloud from the depth image, then clip it using a small rectangular cuboid. Then send the clipped depth image into ScalableTSDFVolume. This should be the easiest way.

Otherwise, you can hack into the C++ code of UniformTSDFVolume and make it rectangular cuboid.

**Comment by martinakos** [comment]
Ok, thanks for the suggestions. I thought about hacking the C++ code for UniformTSDFVolume. I see there is a resolution_ variable that I could replace by resolution_x, resolution_y, resolution_z, maybe I'm lucky and it works. If it doesn't it may take me more time to get to hack it and I'll have to think if I use the time as in principle I'm just doing a demo, not a production quality app. 
Clipping the point clouds to a cuboid before passing them to ScalableTSDFVolume sounds it could do the trick, so I may try this first.
