### ISSUE TITLE
3d scanner with Reconstruction system and measurement - Question 

### ISSUE THREAD

**Issue by giginap** [intel-isl/Open3D#643]
Hi,
Is it Possible to reconstruct an object from a depth camera(realsense D400) and convert into a mesh model? and then make a mesurement process on it.

Thanks

**Comment by yxlao** [comment]
Please refer to this release video for an example on reconstruction with realsense camera: https://www.youtube.com/watch?v=6FkbxLLZyFQ

**Comment by giginap** [comment]
thank you yxlao, 

are you planning to develop a real-time reconstruction and also do you have any advice to optimize in spread the reconstruction system?

**Comment by qianyizh** [comment]
We don't have plan for a real-time reconstruction system yet. The main reason is that the current system is built completely on C++ and without GPU acceleration it is very hard to make it real time.

The best practice in terms of optimization is to sample less frames (e.g., sample 10fps), and use larger fragments (e.g., 3s fragments). This way you reduce the size of the graph. And the accuracy does not drop much. Many very good previous work does similar things too (e.g., RGB-D odometry).

For global registration, FastGlobalRegistration is much faster than RANSAC but it sacrifices some accuracy. So be careful of it.

For ICP, always use a HybridSearchParameter, it is much faster than KNN and RadiusSearch. But I think this has been made default in our tutorial.

For integration, use ScalableTSDF instead of UniformTSDF. The former is much faster.

There are some parameters to tune. I think the ones in the tutorials have been tuned to achieve a good balance between accuracy, robustness, and speed.

**Comment by rafael2k** [comment]
Hi all,
I don't really understand the need of the fragment. I'm writing an offline scanner, and I'm capturing from Kinect2 using freenect, then aligning the PCs created from the captured RGB+D using FastGlobalRegistration. The transformation matrix from the registration result I feed the volume.Integrate extrinsic. Is this correct? 
It seems almost working here.

**Comment by qianyizh** [comment]
The purpose of fragment is to integrate a number of consecutive RGB-D frames to create geometry with less noise. If in your use case the raw RGB-D frames work well then there is no need for fragments.

**Comment by TheodoreT** [comment]
@qianyizh or anyone else that might knows. I am want to create an online (for the moment offline is also fine) volumetric 3D map of an environment using the realsense. I followed the instructions from the [Reconstruction System](http://www.open3d.org/docs/tutorial/ReconstructionSystem/index.html) tutorial but my output is quite bad as you can see below:

![image](https://user-images.githubusercontent.com/10189018/55487872-39854e00-562f-11e9-916d-c0646e45f458.png)

![image](https://user-images.githubusercontent.com/10189018/55487947-60dc1b00-562f-11e9-866f-ca98f2eb7774.png)

I have recorded the scene quite a few times but the result is always quite bad. Thus, I was wondering if you guys have any hints regarding how I can improve the reconstruction. I am using the default settings as provided in the tutorial scripts.

Also another question is how the open3d approach compares to the [fastfusion](https://github.com/tum-vision/fastfusion) solution in terms of accuracy (my guess is that open3d is better here) and speed (I guess that fastfusion is better here) and whether these two could be combined somehow in order to provide a cpu-based real time solution in open3d as well.

**Comment by qianyizh** [comment]
I haven't got much first hand experience of Realsense. (TBH, I think its accuracy is pretty bad, at least in its DS400 series.) @syncle has some success with realsense cameras. He may be able to help you or give you a few pointers to start with.

**Comment by germanros1987** [comment]
Issue closed due to lack of activity. Feel free to open a new issue if you still consider this is a critical matter.
