### ISSUE TITLE
Different point sizes for different clouds in visualizer

### ISSUE THREAD

**Issue by atenpas** [intel-isl/Open3D#782]
Is it possible to draw two point clouds with different point sizes? For example, the first cloud with size of 1cm and the second with size of 2cm. The equivalent option in PCL would be something like PointCloudRenderingProperties, PointSize (from the top of my head).

**Comment by syncle** [comment]
Hi @atenpas, that's interesting question, but It is not possible with current Open3D version (as of 0.5 pre). This is because the point size in a window is globally controlled by single ``RenderOption``. This means a window will have a single setting for point cloud size.

One workaround for your case is to use sphere primitive - you are using explicit spheres to draw point clouds, so that you can control the size of individual points. Please take a look ``create_mesh_sphere``. The downside of this method is - it is not an efficient option if there are too many points (let's say millions) you wanted to draw.

**Comment by YishaiEArbe** [comment]
yes, please!

**Comment by errissa** [comment]
@YishaiEArbe It is possible to set point size per point cloud with the new visualizer. Please see the examples in `examples/Python/visualization`.

**Comment by errissa** [comment]
Here's a quick example of how to set point size using `MaterialRecord`:
```
import numpy as np
import open3d as o3d

def make_point_cloud(npts, center, radius, colorize):
     pts = np.random.uniform(-radius, radius, size=[npts, 3]) + center
     cloud = o3d.geometry.PointCloud()
     cloud.points = o3d.utility.Vector3dVector(pts)
     if colorize:
         colors = np.random.uniform(0.0, 1.0, size=[npts, 3])
         cloud.colors = o3d.utility.Vector3dVector(colors)
     return cloud

pcd = make_point_cloud(100, (0,0,0), 2.0, True)

mat = o3d.visualization.rendering.MaterialRecord()
mat.shader = 'defaultUnlit'
mat.point_size = 9.0

o3d.visualization.draw([{'name': 'pcd', 'geometry': pcd, 'material': mat}], show_skybox=False)
```

**Comment by ljyjjcj** [comment]
Thank @errissa for your reply for the different size of the point cloud.

I have one quick question.
Can I apply the material properities to a case of point cloud rendering in a while loop?
Both o3d.visualization.Visualizer.add_geometry and o3d.visualization.Visualizer.update_geometry do not have parameter for the material.
Anyone can help this?

**Comment by jashmehta20** [comment]
I have the same question. I'm running a while loop where I'm updating the point cloud using .add_geometry( ) and .update_renderer( ). How would I change the point cloud point size then?
