### ISSUE TITLE
VortexGrid and GlobalOptimization compilation problem on Ubuntu

### ISSUE THREAD

**Issue by WenyinWei** [intel-isl/Open3D#935]
**Describe the bug**
Seems the compilation can not succeed, any idea to fix it?
The problem arises when I compiled the VortexGrid.cpp and GlobalOptimization.cpp.

**To Reproduce**
1. git clone --recursive https://github.com/intel-isl/Open3D
2. cd Open3D |  . util/scripts/install-deps-ubuntu.sh
3. mkdir build | cd build
4. cmake ..
3. make -j8 and meets the problem.

**Expected behavior**
Seems the compilation can not succeed, any idea to fix it?

**Screenshots**

![image](https://user-images.githubusercontent.com/33152225/56848164-2f95f880-6918-11e9-9084-d56abd6256bf.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version:3.6
 - Open3D version: The latest from git.
 - Is this remote workstation?: no
 - How did you install Open3D?: gcc build from source

**Additional context**
It looks like that there are many compatibility bugs hidden in Open3D, but it seems to be an almost perfect open source package except for the bugs. I hope I could be a contributor to fix them.

**Comment by WenyinWei** [comment]
This problem is fixed by changing 
```
Eigen::Vector3i VoxelGrid::GetVoxel(const Eigen::Vector3d &point) const {
    Eigen::Vector3d voxel_f = (point - origin_) / voxel_size_;
    return Eigen::floor(voxel_f.array()).cast<int>();
}
```
to 
```
Eigen::Vector3i VoxelGrid::GetVoxel(const Eigen::Vector3d &point) const {
    Eigen::Vector3d voxel_f = (point - origin_) / voxel_size_;
    return (Eigen::floor(voxel_f.array())).cast<int>();
}
```
The compiler can not recognize the sequence, so a bracket could solve the problem.

**Comment by yxlao** [comment]
@WenyinWei thanks for reporting, we have another user reporting the same issue. 

From both cases, it looks like Open3D is picking up the system's Eigen, instead of the Eigen that comes with Open3D's `3rdparty` directory. In that particular case, the `floor` function is missing in the `GlobalFunctions.h` file, but it should look like https://github.com/eigenteam/eigen-git-mirror/blob/ed95dad9783d0cab2275679e028f23ac18c0d1f1/Eigen/src/Core/GlobalFunctions.h#L92

The solution we got it to work is to force Open3D to use the Eigen that comes with it in the 3rd party directory. That is,
```shell
cmake -DBUILD_EIGEN3=ON ..
```

We'll update Open3D's 3rd party CMake file to make that the default behavior.

**Comment by WenyinWei** [comment]
Thanks for your reply, @yxlao.

Do you think that setting the default cmake options of 3rd party packages to ON would be better for new users to compile and avoid the bugs caused by 3rd party package updating? I guess that it would be more convenient to keep every user the same configuration.

**Comment by yxlao** [comment]
@WenyinWei yeah, we'll make it to be `ON` by default

**Comment by germanros1987** [comment]
Is it solved?

**Comment by germanros1987** [comment]
Solved.
